// Generated by CIRCT firtool-1.138.0
module elasticArbiter(
  input         clock,
                reset,
  input  [31:0] io_sources_0_bits,
  input         io_sources_0_valid,
  output        io_sources_0_ready,
  input  [31:0] io_sources_1_bits,
  input         io_sources_1_valid,
  output        io_sources_1_ready,
  input  [31:0] io_sources_2_bits,
  input         io_sources_2_valid,
  output        io_sources_2_ready,
  input  [31:0] io_sources_3_bits,
  input         io_sources_3_valid,
  output        io_sources_3_ready,
  input  [31:0] io_sources_4_bits,
  input         io_sources_4_valid,
  output        io_sources_4_ready,
  input  [31:0] io_sources_5_bits,
  input         io_sources_5_valid,
  output        io_sources_5_ready,
  input  [31:0] io_sources_6_bits,
  input         io_sources_6_valid,
  output        io_sources_6_ready,
  input  [31:0] io_sources_7_bits,
  input         io_sources_7_valid,
  output        io_sources_7_ready,
  input  [31:0] io_sources_8_bits,
  input         io_sources_8_valid,
  output        io_sources_8_ready,
  input  [31:0] io_sources_9_bits,
  input         io_sources_9_valid,
  output        io_sources_9_ready,
  input  [31:0] io_sources_10_bits,
  input         io_sources_10_valid,
  output        io_sources_10_ready,
  input  [31:0] io_sources_11_bits,
  input         io_sources_11_valid,
  output        io_sources_11_ready,
  input  [31:0] io_sources_12_bits,
  input         io_sources_12_valid,
  output        io_sources_12_ready,
  input  [31:0] io_sources_13_bits,
  input         io_sources_13_valid,
  output        io_sources_13_ready,
  input  [31:0] io_sources_14_bits,
  input         io_sources_14_valid,
  output        io_sources_14_ready,
  input  [31:0] io_sources_15_bits,
  input         io_sources_15_valid,
  output        io_sources_15_ready,
  output [31:0] io_sink_bits,
  output        io_sink_valid,
  input         io_sink_ready,
  output [3:0]  io_select_bits,
  output        io_select_valid,
  input         io_select_ready
);

  reg               regSink;
  reg               regSelect;
  wire              _regSink_T = io_sink_ready | regSink;
  wire              _regSelect_T = io_select_ready | regSelect;
  wire              ready = _regSink_T & _regSelect_T;
  reg  [3:0]        choice_last;
  wire [3:0]        choice_rr0 =
    (&choice_last)
      ? 4'h0
      : choice_last == 4'h0 & io_sources_1_valid
          ? 4'h1
          : choice_last < 4'h2 & io_sources_2_valid
              ? 4'h2
              : choice_last < 4'h3 & io_sources_3_valid
                  ? 4'h3
                  : choice_last < 4'h4 & io_sources_4_valid
                      ? 4'h4
                      : choice_last < 4'h5 & io_sources_5_valid
                          ? 4'h5
                          : choice_last < 4'h6 & io_sources_6_valid
                              ? 4'h6
                              : choice_last < 4'h7 & io_sources_7_valid
                                  ? 4'h7
                                  : ~(choice_last[3]) & io_sources_8_valid
                                      ? 4'h8
                                      : choice_last < 4'h9 & io_sources_9_valid
                                          ? 4'h9
                                          : choice_last < 4'hA & io_sources_10_valid
                                              ? 4'hA
                                              : choice_last < 4'hB & io_sources_11_valid
                                                  ? 4'hB
                                                  : choice_last[3:2] != 2'h3
                                                    & io_sources_12_valid
                                                      ? 4'hC
                                                      : choice_last < 4'hD
                                                        & io_sources_13_valid
                                                          ? 4'hD
                                                          : {3'h7,
                                                             ~(choice_last[3:1] != 3'h7
                                                               & io_sources_14_valid)};
  wire [15:0]       _GEN =
    {{io_sources_15_valid},
     {io_sources_14_valid},
     {io_sources_13_valid},
     {io_sources_12_valid},
     {io_sources_11_valid},
     {io_sources_10_valid},
     {io_sources_9_valid},
     {io_sources_8_valid},
     {io_sources_7_valid},
     {io_sources_6_valid},
     {io_sources_5_valid},
     {io_sources_4_valid},
     {io_sources_3_valid},
     {io_sources_2_valid},
     {io_sources_1_valid},
     {io_sources_0_valid}};
  wire [3:0]        choice_rr =
    _GEN[choice_rr0]
      ? choice_rr0
      : io_sources_0_valid
          ? 4'h0
          : io_sources_1_valid
              ? 4'h1
              : io_sources_2_valid
                  ? 4'h2
                  : io_sources_3_valid
                      ? 4'h3
                      : io_sources_4_valid
                          ? 4'h4
                          : io_sources_5_valid
                              ? 4'h5
                              : io_sources_6_valid
                                  ? 4'h6
                                  : io_sources_7_valid
                                      ? 4'h7
                                      : io_sources_8_valid
                                          ? 4'h8
                                          : io_sources_9_valid
                                              ? 4'h9
                                              : io_sources_10_valid
                                                  ? 4'hA
                                                  : io_sources_11_valid
                                                      ? 4'hB
                                                      : io_sources_12_valid
                                                          ? 4'hC
                                                          : io_sources_13_valid
                                                              ? 4'hD
                                                              : {3'h7,
                                                                 ~io_sources_14_valid};
  reg               choice_locked;
  reg  [3:0]        choice_lockedChoice;
  wire [3:0]        choice = choice_locked ? choice_lockedChoice : choice_rr;
  wire [15:0][31:0] _GEN_0 =
    {{io_sources_15_bits},
     {io_sources_14_bits},
     {io_sources_13_bits},
     {io_sources_12_bits},
     {io_sources_11_bits},
     {io_sources_10_bits},
     {io_sources_9_bits},
     {io_sources_8_bits},
     {io_sources_7_bits},
     {io_sources_6_bits},
     {io_sources_5_bits},
     {io_sources_4_bits},
     {io_sources_3_bits},
     {io_sources_2_bits},
     {io_sources_1_bits},
     {io_sources_0_bits}};
  always @(posedge clock) begin
    if (reset) begin
      regSink <= 1'h0;
      regSelect <= 1'h0;
      choice_last <= 4'h0;
      choice_locked <= 1'h0;
      choice_lockedChoice <= 4'h0;
    end
    else begin
      regSink <= _regSink_T & _GEN[choice] & ~ready;
      regSelect <= _regSelect_T & _GEN[choice] & ~ready;
      if (_GEN[choice] & ready)
        choice_last <= choice;
      choice_locked <= _GEN[choice] & ~ready;
      if (choice_locked) begin
      end
      else
        choice_lockedChoice <= choice_rr;
    end
  end // always @(posedge)
  assign io_sources_0_ready = ready & choice == 4'h0;
  assign io_sources_1_ready = ready & choice == 4'h1;
  assign io_sources_2_ready = ready & choice == 4'h2;
  assign io_sources_3_ready = ready & choice == 4'h3;
  assign io_sources_4_ready = ready & choice == 4'h4;
  assign io_sources_5_ready = ready & choice == 4'h5;
  assign io_sources_6_ready = ready & choice == 4'h6;
  assign io_sources_7_ready = ready & choice == 4'h7;
  assign io_sources_8_ready = ready & choice == 4'h8;
  assign io_sources_9_ready = ready & choice == 4'h9;
  assign io_sources_10_ready = ready & choice == 4'hA;
  assign io_sources_11_ready = ready & choice == 4'hB;
  assign io_sources_12_ready = ready & choice == 4'hC;
  assign io_sources_13_ready = ready & choice == 4'hD;
  assign io_sources_14_ready = ready & choice == 4'hE;
  assign io_sources_15_ready = ready & (&choice);
  assign io_sink_bits = _GEN_0[choice];
  assign io_sink_valid = _GEN[choice] & ~regSink;
  assign io_select_bits = choice;
  assign io_select_valid = _GEN[choice] & ~regSelect;
endmodule

module Arbiter_Tbtop(
  input         clock,
                reset,
  input  [31:0] rr_sources_00_bits,
  input         rr_sources_00_valid,
  output        rr_sources_00_ready,
  input  [31:0] rr_sources_01_bits,
  input         rr_sources_01_valid,
  output        rr_sources_01_ready,
  input  [31:0] rr_sources_02_bits,
  input         rr_sources_02_valid,
  output        rr_sources_02_ready,
  input  [31:0] rr_sources_03_bits,
  input         rr_sources_03_valid,
  output        rr_sources_03_ready,
  input  [31:0] rr_sources_04_bits,
  input         rr_sources_04_valid,
  output        rr_sources_04_ready,
  input  [31:0] rr_sources_05_bits,
  input         rr_sources_05_valid,
  output        rr_sources_05_ready,
  input  [31:0] rr_sources_06_bits,
  input         rr_sources_06_valid,
  output        rr_sources_06_ready,
  input  [31:0] rr_sources_07_bits,
  input         rr_sources_07_valid,
  output        rr_sources_07_ready,
  input  [31:0] rr_sources_08_bits,
  input         rr_sources_08_valid,
  output        rr_sources_08_ready,
  input  [31:0] rr_sources_09_bits,
  input         rr_sources_09_valid,
  output        rr_sources_09_ready,
  input  [31:0] rr_sources_10_bits,
  input         rr_sources_10_valid,
  output        rr_sources_10_ready,
  input  [31:0] rr_sources_11_bits,
  input         rr_sources_11_valid,
  output        rr_sources_11_ready,
  input  [31:0] rr_sources_12_bits,
  input         rr_sources_12_valid,
  output        rr_sources_12_ready,
  input  [31:0] rr_sources_13_bits,
  input         rr_sources_13_valid,
  output        rr_sources_13_ready,
  input  [31:0] rr_sources_14_bits,
  input         rr_sources_14_valid,
  output        rr_sources_14_ready,
  input  [31:0] rr_sources_15_bits,
  input         rr_sources_15_valid,
  output        rr_sources_15_ready,
  output [31:0] rr_sink_bits,
  output        rr_sink_valid,
  input         rr_sink_ready,
  output [3:0]  rr_select_bits,
  output        rr_select_valid,
  input         rr_select_ready,
  input  [31:0] priority_sources_00_bits,
  input         priority_sources_00_valid,
  output        priority_sources_00_ready,
  input  [31:0] priority_sources_01_bits,
  input         priority_sources_01_valid,
  output        priority_sources_01_ready,
  input  [31:0] priority_sources_02_bits,
  input         priority_sources_02_valid,
  output        priority_sources_02_ready,
  input  [31:0] priority_sources_03_bits,
  input         priority_sources_03_valid,
  output        priority_sources_03_ready,
  input  [31:0] priority_sources_04_bits,
  input         priority_sources_04_valid,
  output        priority_sources_04_ready,
  input  [31:0] priority_sources_05_bits,
  input         priority_sources_05_valid,
  output        priority_sources_05_ready,
  input  [31:0] priority_sources_06_bits,
  input         priority_sources_06_valid,
  output        priority_sources_06_ready,
  input  [31:0] priority_sources_07_bits,
  input         priority_sources_07_valid,
  output        priority_sources_07_ready,
  input  [31:0] priority_sources_08_bits,
  input         priority_sources_08_valid,
  output        priority_sources_08_ready,
  input  [31:0] priority_sources_09_bits,
  input         priority_sources_09_valid,
  output        priority_sources_09_ready,
  input  [31:0] priority_sources_10_bits,
  input         priority_sources_10_valid,
  output        priority_sources_10_ready,
  input  [31:0] priority_sources_11_bits,
  input         priority_sources_11_valid,
  output        priority_sources_11_ready,
  input  [31:0] priority_sources_12_bits,
  input         priority_sources_12_valid,
  output        priority_sources_12_ready,
  input  [31:0] priority_sources_13_bits,
  input         priority_sources_13_valid,
  output        priority_sources_13_ready,
  input  [31:0] priority_sources_14_bits,
  input         priority_sources_14_valid,
  output        priority_sources_14_ready,
  input  [31:0] priority_sources_15_bits,
  input         priority_sources_15_valid,
  output        priority_sources_15_ready,
  output [31:0] priority_sink_bits,
  output        priority_sink_valid,
  input         priority_sink_ready,
  output [3:0]  priority_select_bits,
  output        priority_select_valid,
  input         priority_select_ready
);

  elasticArbiter arbiter (
    .clock               (clock),
    .reset               (reset),
    .io_sources_0_bits   (rr_sources_00_bits),
    .io_sources_0_valid  (rr_sources_00_valid),
    .io_sources_0_ready  (rr_sources_00_ready),
    .io_sources_1_bits   (rr_sources_01_bits),
    .io_sources_1_valid  (rr_sources_01_valid),
    .io_sources_1_ready  (rr_sources_01_ready),
    .io_sources_2_bits   (rr_sources_02_bits),
    .io_sources_2_valid  (rr_sources_02_valid),
    .io_sources_2_ready  (rr_sources_02_ready),
    .io_sources_3_bits   (rr_sources_03_bits),
    .io_sources_3_valid  (rr_sources_03_valid),
    .io_sources_3_ready  (rr_sources_03_ready),
    .io_sources_4_bits   (rr_sources_04_bits),
    .io_sources_4_valid  (rr_sources_04_valid),
    .io_sources_4_ready  (rr_sources_04_ready),
    .io_sources_5_bits   (rr_sources_05_bits),
    .io_sources_5_valid  (rr_sources_05_valid),
    .io_sources_5_ready  (rr_sources_05_ready),
    .io_sources_6_bits   (rr_sources_06_bits),
    .io_sources_6_valid  (rr_sources_06_valid),
    .io_sources_6_ready  (rr_sources_06_ready),
    .io_sources_7_bits   (rr_sources_07_bits),
    .io_sources_7_valid  (rr_sources_07_valid),
    .io_sources_7_ready  (rr_sources_07_ready),
    .io_sources_8_bits   (rr_sources_08_bits),
    .io_sources_8_valid  (rr_sources_08_valid),
    .io_sources_8_ready  (rr_sources_08_ready),
    .io_sources_9_bits   (rr_sources_09_bits),
    .io_sources_9_valid  (rr_sources_09_valid),
    .io_sources_9_ready  (rr_sources_09_ready),
    .io_sources_10_bits  (rr_sources_10_bits),
    .io_sources_10_valid (rr_sources_10_valid),
    .io_sources_10_ready (rr_sources_10_ready),
    .io_sources_11_bits  (rr_sources_11_bits),
    .io_sources_11_valid (rr_sources_11_valid),
    .io_sources_11_ready (rr_sources_11_ready),
    .io_sources_12_bits  (rr_sources_12_bits),
    .io_sources_12_valid (rr_sources_12_valid),
    .io_sources_12_ready (rr_sources_12_ready),
    .io_sources_13_bits  (rr_sources_13_bits),
    .io_sources_13_valid (rr_sources_13_valid),
    .io_sources_13_ready (rr_sources_13_ready),
    .io_sources_14_bits  (rr_sources_14_bits),
    .io_sources_14_valid (rr_sources_14_valid),
    .io_sources_14_ready (rr_sources_14_ready),
    .io_sources_15_bits  (rr_sources_15_bits),
    .io_sources_15_valid (rr_sources_15_valid),
    .io_sources_15_ready (rr_sources_15_ready),
    .io_sink_bits        (rr_sink_bits),
    .io_sink_valid       (rr_sink_valid),
    .io_sink_ready       (rr_sink_ready),
    .io_select_bits      (rr_select_bits),
    .io_select_valid     (rr_select_valid),
    .io_select_ready     (rr_select_ready)
  );
  elasticArbiter arbiter_1 (
    .clock               (clock),
    .reset               (reset),
    .io_sources_0_bits   (priority_sources_00_bits),
    .io_sources_0_valid  (priority_sources_00_valid),
    .io_sources_0_ready  (priority_sources_00_ready),
    .io_sources_1_bits   (priority_sources_01_bits),
    .io_sources_1_valid  (priority_sources_01_valid),
    .io_sources_1_ready  (priority_sources_01_ready),
    .io_sources_2_bits   (priority_sources_02_bits),
    .io_sources_2_valid  (priority_sources_02_valid),
    .io_sources_2_ready  (priority_sources_02_ready),
    .io_sources_3_bits   (priority_sources_03_bits),
    .io_sources_3_valid  (priority_sources_03_valid),
    .io_sources_3_ready  (priority_sources_03_ready),
    .io_sources_4_bits   (priority_sources_04_bits),
    .io_sources_4_valid  (priority_sources_04_valid),
    .io_sources_4_ready  (priority_sources_04_ready),
    .io_sources_5_bits   (priority_sources_05_bits),
    .io_sources_5_valid  (priority_sources_05_valid),
    .io_sources_5_ready  (priority_sources_05_ready),
    .io_sources_6_bits   (priority_sources_06_bits),
    .io_sources_6_valid  (priority_sources_06_valid),
    .io_sources_6_ready  (priority_sources_06_ready),
    .io_sources_7_bits   (priority_sources_07_bits),
    .io_sources_7_valid  (priority_sources_07_valid),
    .io_sources_7_ready  (priority_sources_07_ready),
    .io_sources_8_bits   (priority_sources_08_bits),
    .io_sources_8_valid  (priority_sources_08_valid),
    .io_sources_8_ready  (priority_sources_08_ready),
    .io_sources_9_bits   (priority_sources_09_bits),
    .io_sources_9_valid  (priority_sources_09_valid),
    .io_sources_9_ready  (priority_sources_09_ready),
    .io_sources_10_bits  (priority_sources_10_bits),
    .io_sources_10_valid (priority_sources_10_valid),
    .io_sources_10_ready (priority_sources_10_ready),
    .io_sources_11_bits  (priority_sources_11_bits),
    .io_sources_11_valid (priority_sources_11_valid),
    .io_sources_11_ready (priority_sources_11_ready),
    .io_sources_12_bits  (priority_sources_12_bits),
    .io_sources_12_valid (priority_sources_12_valid),
    .io_sources_12_ready (priority_sources_12_ready),
    .io_sources_13_bits  (priority_sources_13_bits),
    .io_sources_13_valid (priority_sources_13_valid),
    .io_sources_13_ready (priority_sources_13_ready),
    .io_sources_14_bits  (priority_sources_14_bits),
    .io_sources_14_valid (priority_sources_14_valid),
    .io_sources_14_ready (priority_sources_14_ready),
    .io_sources_15_bits  (priority_sources_15_bits),
    .io_sources_15_valid (priority_sources_15_valid),
    .io_sources_15_ready (priority_sources_15_ready),
    .io_sink_bits        (priority_sink_bits),
    .io_sink_valid       (priority_sink_valid),
    .io_sink_ready       (priority_sink_ready),
    .io_select_bits      (priority_select_bits),
    .io_select_valid     (priority_select_valid),
    .io_select_ready     (priority_select_ready)
  );
endmodule

