// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// external module chext_mem_1w1r

// external module chext_mem_1w1r

module elasticMux(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:9:7
  output        io_sources_0_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  input         io_sources_0_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  input  [63:0] io_sources_0_bits,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  output        io_sources_1_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  input         io_sources_1_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  input  [63:0] io_sources_1_bits,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  input         io_sink_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  output        io_sink_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  output [63:0] io_sink_bits,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  output        io_select_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
  input         io_select_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
                io_select_bits	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:19:14
);

  wire valid =
    io_select_valid & (io_select_bits ? io_sources_1_valid : io_sources_0_valid);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:29:39
  wire fire = valid & io_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:29:39, :30:28
  assign io_sources_0_ready = fire & ~io_select_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:9:7, :30:28, :34:{21,28}
  assign io_sources_1_ready = fire & io_select_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:9:7, :30:28, :34:21
  assign io_sink_valid = valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:9:7, :29:39
  assign io_sink_bits = io_select_bits ? io_sources_1_bits : io_sources_0_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:9:7, :29:39
  assign io_select_ready = fire;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:9:7, :30:28
endmodule

// external module chext_mem_1w1r

module elasticDemux(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:8:7
  output        io_source_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  input         io_source_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  input  [63:0] io_source_bits,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  input         io_sinks_0_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  output        io_sinks_0_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  output [63:0] io_sinks_0_bits,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  input         io_sinks_1_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  output        io_sinks_1_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  output [63:0] io_sinks_1_bits,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  output        io_select_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
  input         io_select_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
                io_select_bits	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:18:14
);

  wire valid = io_select_valid & io_source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:28:39
  wire fire = valid & (io_select_bits ? io_sinks_1_ready : io_sinks_0_ready);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:28:39, :29:28
  assign io_source_ready = fire;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:8:7, :29:28
  assign io_sinks_0_valid = valid & ~io_select_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:8:7, :28:39, :36:{22,30}
  assign io_sinks_0_bits = io_source_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:8:7
  assign io_sinks_1_valid = valid & io_select_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:8:7, :28:39, :36:22
  assign io_sinks_1_bits = io_source_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:8:7
  assign io_select_ready = fire;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:8:7, :29:28
endmodule

module Fold_Tbtop(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
  input         clock,	// <stdin>:348:11
                reset,	// <stdin>:349:11
  output        source_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:8:18
  input         source_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:8:18
                source_bits_zero,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:8:18
                source_bits_last,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:8:18
  input  [31:0] source_bits_data,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:8:18
  input         sink_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:14:16
  output        sink_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:14:16
  output [31:0] sink_bits_result	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:14:16
);

  wire        fold0_stage1_fork0_leftBuffer_sink_1_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_sink_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        _fold0_stage2_fork0_mux_io_sources_0_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire        _fold0_stage2_fork0_mux_io_sources_1_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire        _fold0_stage2_fork0_mux_io_sink_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire [63:0] _fold0_stage2_fork0_mux_io_sink_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire        _fold0_stage2_fork0_mux_io_select_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire        _fold0_stage2_fork0_demux_1_io_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire        _fold0_stage2_fork0_demux_1_io_sinks_1_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire [63:0] _fold0_stage2_fork0_demux_1_io_sinks_1_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire        _fold0_stage2_fork0_demux_1_io_select_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire        _fold0_stage2_fork0_demux_io_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire        _fold0_stage2_fork0_demux_io_select_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire        _fold0_stage1_fork0_demux_io_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire        _fold0_stage1_fork0_demux_io_sinks_1_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire [63:0] _fold0_stage1_fork0_demux_io_sinks_1_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
  wire        _fold0_stage1_fork0_mux_io_sink_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire [63:0] _fold0_stage1_fork0_mux_io_sink_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire [66:0] _fold0_stage1_fork0_transform0_leftBuffer_ram_dataOutB;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_source_bits_last =
    source_bits_last;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_source_bits_zero =
    source_bits_zero;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_source_1_bits = source_bits_last;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire [63:0] fold0_sinkA_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire [63:0] fold0_sinkB_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  reg  [31:0] fold0_count;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:41:26
  wire        _fold0_T = sink_ready & _fold0_stage1_fork0_demux_io_sinks_1_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23, src/main/scala/chisel3/util/Decoupled.scala:51:35
  reg         fold0_stage0_transducerFirstLogic_state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_source_bits_first =
    fold0_stage0_transducerFirstLogic_state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_source_bits =
    fold0_stage0_transducerFirstLogic_state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire [63:0] fold0_stage1_fork0_transform0_leftBuffer_source_bits_operand =
    {{32{source_bits_data[31]}}, source_bits_data};	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  reg         fold0_stage1_fork0_transform0_leftBuffer_wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_transform0_leftBuffer_wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_transform0_leftBuffer_maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_ptr_match =
    fold0_stage1_fork0_transform0_leftBuffer_wrap == fold0_stage1_fork0_transform0_leftBuffer_wrap_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Counter.scala:61:40
  wire        fold0_stage1_fork0_transform0_leftBuffer_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_do_enq =
    fold0_stage1_fork0_transform0_leftBuffer_source_ready
    & fold0_stage1_fork0_transform0_leftBuffer_source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire        fold0_stage1_fork0_transform0_leftBuffer_sink_valid =
    ~(fold0_stage1_fork0_transform0_leftBuffer_ptr_match
      & ~fold0_stage1_fork0_transform0_leftBuffer_maybe_full);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_sink_bits_zero =
    _fold0_stage1_fork0_transform0_leftBuffer_ram_dataOutB[0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_sink_bits_last =
    _fold0_stage1_fork0_transform0_leftBuffer_ram_dataOutB[1];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_sink_bits_first =
    _fold0_stage1_fork0_transform0_leftBuffer_ram_dataOutB[2];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_transform0_leftBuffer_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire [63:0] fold0_stage1_fork0_transform0_leftBuffer_sink_bits_operand =
    _fold0_stage1_fork0_transform0_leftBuffer_ram_dataOutB[66:3];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_stage1_fork0_transform0_leftBuffer_source_ready =
    fold0_stage1_fork0_transform0_leftBuffer_sink_ready
    | ~(fold0_stage1_fork0_transform0_leftBuffer_ptr_match
        & fold0_stage1_fork0_transform0_leftBuffer_maybe_full);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  reg         fold0_stage1_fork0_leftBuffer_wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_leftBuffer_wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_leftBuffer_maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_ptr_match =
    fold0_stage1_fork0_leftBuffer_wrap == fold0_stage1_fork0_leftBuffer_wrap_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Counter.scala:61:40
  wire        fold0_stage1_fork0_leftBuffer_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_do_enq =
    fold0_stage1_fork0_leftBuffer_source_ready
    & fold0_stage1_fork0_leftBuffer_source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire        fold0_stage1_fork0_leftBuffer_sink_valid =
    ~(fold0_stage1_fork0_leftBuffer_ptr_match
      & ~fold0_stage1_fork0_leftBuffer_maybe_full);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_stage1_fork0_leftBuffer_source_ready =
    fold0_stage1_fork0_leftBuffer_sink_ready
    | ~(fold0_stage1_fork0_leftBuffer_ptr_match
        & fold0_stage1_fork0_leftBuffer_maybe_full);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  reg         fold0_stage1_fork0_rightBuffer_wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_rightBuffer_wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_rightBuffer_maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_rightBuffer_ptr_match =
    fold0_stage1_fork0_rightBuffer_wrap == fold0_stage1_fork0_rightBuffer_wrap_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Counter.scala:61:40
  wire        fold0_stage1_fork0_rightBuffer_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_rightBuffer_source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_rightBuffer_do_enq =
    fold0_stage1_fork0_rightBuffer_source_ready
    & fold0_stage1_fork0_rightBuffer_source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire        fold0_stage1_fork0_rightBuffer_sink_valid =
    ~(fold0_stage1_fork0_rightBuffer_ptr_match
      & ~fold0_stage1_fork0_rightBuffer_maybe_full);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_stage1_fork0_rightBuffer_source_ready =
    ~(fold0_stage1_fork0_rightBuffer_ptr_match
      & fold0_stage1_fork0_rightBuffer_maybe_full);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  reg         fold0_stage1_fork0_leftBuffer_wrap_2;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_leftBuffer_wrap_3;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         fold0_stage1_fork0_leftBuffer_maybe_full_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_ptr_match_1 =
    fold0_stage1_fork0_leftBuffer_wrap_2 == fold0_stage1_fork0_leftBuffer_wrap_3;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Counter.scala:61:40
  wire        fold0_stage1_fork0_leftBuffer_source_1_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_source_1_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_do_enq_1 =
    fold0_stage1_fork0_leftBuffer_source_1_ready
    & fold0_stage1_fork0_leftBuffer_source_1_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire        fold0_stage1_fork0_leftBuffer_sink_1_valid =
    ~(fold0_stage1_fork0_leftBuffer_ptr_match_1
      & ~fold0_stage1_fork0_leftBuffer_maybe_full_1);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_leftBuffer_sink_1_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_sinkA_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_sinkB_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_stage1_fork0_leftBuffer_source_1_ready =
    fold0_stage1_fork0_leftBuffer_sink_1_ready
    | ~(fold0_stage1_fork0_leftBuffer_ptr_match_1
        & fold0_stage1_fork0_leftBuffer_maybe_full_1);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_join0_allValid = fold0_sinkA_valid & fold0_sinkB_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Join.scala:53:53, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_join0_fire =
    _fold0_stage2_fork0_mux_io_sources_0_ready & fold0_join0_allValid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Join.scala:53:53, :54:27, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  wire        fold0_sinkA_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_sinkA_ready = fold0_join0_fire;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Join.scala:54:27, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_sinkB_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_sinkB_ready = fold0_join0_fire;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Join.scala:54:27, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  reg         fold0_stage2_fork0_regs_0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23
  reg         fold0_stage2_fork0_regs_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23
  reg         fold0_stage2_fork0_regs_2;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23
  reg         fold0_stage2_fork0_regs_3;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23
  wire        fold0_stage2_fork0_ready_qual1_0 =
    _fold0_stage2_fork0_demux_io_source_ready | fold0_stage2_fork0_regs_0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20
  wire        fold0_stage2_fork0_ready_qual1_1 =
    _fold0_stage2_fork0_demux_io_select_ready | fold0_stage2_fork0_regs_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20
  wire        fold0_stage2_fork0_ready_qual1_2 =
    _fold0_stage2_fork0_demux_1_io_select_ready | fold0_stage2_fork0_regs_2;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20
  wire        fold0_stage2_fork0_ready_qual1_3 =
    _fold0_stage2_fork0_mux_io_select_ready | fold0_stage2_fork0_regs_3;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
  assign fold0_stage1_fork0_transform0_leftBuffer_sink_ready =
    fold0_stage2_fork0_ready_qual1_0 & fold0_stage2_fork0_ready_qual1_1
    & fold0_stage2_fork0_ready_qual1_2 & fold0_stage2_fork0_ready_qual1_3;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:59:20, :61:21, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  reg         fold0_stage1_fork0_regs_0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23
  reg         fold0_stage1_fork0_regs_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23
  reg         fold0_stage1_fork0_regs_2;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23
  wire        fold0_stage1_fork0_ready_qual1_0 =
    fold0_stage1_fork0_transform0_leftBuffer_source_ready | fold0_stage1_fork0_regs_0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_ready_qual1_1 =
    fold0_stage1_fork0_leftBuffer_source_ready | fold0_stage1_fork0_regs_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage1_fork0_ready_qual1_2 =
    fold0_stage1_fork0_leftBuffer_source_1_ready | fold0_stage1_fork0_regs_2;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage0_ready =
    fold0_stage1_fork0_ready_qual1_0 & fold0_stage1_fork0_ready_qual1_1
    & fold0_stage1_fork0_ready_qual1_2;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:59:20, :61:21
  assign fold0_stage1_fork0_transform0_leftBuffer_source_valid =
    source_valid & ~fold0_stage1_fork0_regs_0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :66:{36,39}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_stage1_fork0_leftBuffer_source_valid =
    source_valid & ~fold0_stage1_fork0_regs_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :66:{36,39}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  assign fold0_stage1_fork0_leftBuffer_source_1_valid =
    source_valid & ~fold0_stage1_fork0_regs_2;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :66:{36,39}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        _GEN = source_valid & fold0_stage0_transducerFirstLogic_state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        _fold0_stage0_transducerFirstLogic_WIRE = _GEN & source_bits_last;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        _fold0_stage0_transducerFirstLogic_WIRE_1 = _GEN & ~source_bits_last;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:58:20, :59:19
  wire        _fold0_stage0_transducerFirstLogic_WIRE_2 =
    source_valid & ~fold0_stage0_transducerFirstLogic_state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:58:20, :59:19
  wire [2:0]  fold0_stage0_transducerFirstLogic_cond =
    {_fold0_stage0_transducerFirstLogic_WIRE_2,
     _fold0_stage0_transducerFirstLogic_WIRE_1,
     _fold0_stage0_transducerFirstLogic_WIRE};	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage0_transducerFirstLogic_errorAtLeastTwoActions =
    source_valid
    & (|(fold0_stage0_transducerFirstLogic_cond
         & {_fold0_stage0_transducerFirstLogic_WIRE_2,
            _fold0_stage0_transducerFirstLogic_WIRE_1,
            _fold0_stage0_transducerFirstLogic_WIRE} - 3'h1));	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  wire        fold0_stage0_transducerFirstLogic_errorNoAction =
    source_valid & fold0_stage0_transducerFirstLogic_cond == 3'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  `ifndef SYNTHESIS	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:44:15
    always @(posedge clock) begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:44:15
      if ((`PRINTF_COND_) & _fold0_T & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:44:15, src/main/scala/chisel3/util/Decoupled.scala:51:35
        $fwrite(32'h80000002, "reduction complete. count = %d\n", fold0_count);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:41:26, :44:15
      if ((`PRINTF_COND_) & fold0_stage0_transducerFirstLogic_errorAtLeastTwoActions
          & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :44:15
        $fwrite(32'h80000002,
                "elastic.Transducer: at least two actions are taken in the same clock cycle!\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :44:15
      if ((`PRINTF_COND_) & fold0_stage0_transducerFirstLogic_errorAtLeastTwoActions
          & _fold0_stage0_transducerFirstLogic_WIRE & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Transducer.scala:235:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :44:15
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala 21:21]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Transducer.scala:235:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:44:15
      if ((`PRINTF_COND_) & fold0_stage0_transducerFirstLogic_errorAtLeastTwoActions
          & _fold0_stage0_transducerFirstLogic_WIRE_1 & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Transducer.scala:235:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :44:15
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala 21:21]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Transducer.scala:235:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:44:15
      if ((`PRINTF_COND_) & fold0_stage0_transducerFirstLogic_errorAtLeastTwoActions
          & _fold0_stage0_transducerFirstLogic_WIRE_2 & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Transducer.scala:235:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :44:15
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala 21:21]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Transducer.scala:235:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:44:15
      if ((`PRINTF_COND_) & fold0_stage0_transducerFirstLogic_errorNoAction & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :44:15
        $fwrite(32'h80000002,
                "elastic.Transducer: no action was taken! @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala 21:21]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :44:15
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        fold0_stage1_fork0_rightBuffer_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  always @(posedge clock) begin	// <stdin>:348:11
    if (reset) begin	// <stdin>:348:11
      fold0_count <= 32'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:41:26
      fold0_stage0_transducerFirstLogic_state <= 1'h1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
      fold0_stage1_fork0_transform0_leftBuffer_wrap <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_transform0_leftBuffer_wrap_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_transform0_leftBuffer_maybe_full <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
      fold0_stage1_fork0_leftBuffer_wrap <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_leftBuffer_wrap_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_leftBuffer_maybe_full <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
      fold0_stage1_fork0_rightBuffer_wrap <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_rightBuffer_wrap_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_rightBuffer_maybe_full <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
      fold0_stage1_fork0_leftBuffer_wrap_2 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_leftBuffer_wrap_3 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, src/main/scala/chisel3/util/Counter.scala:61:40
      fold0_stage1_fork0_leftBuffer_maybe_full_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
      fold0_stage2_fork0_regs_0 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      fold0_stage2_fork0_regs_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      fold0_stage2_fork0_regs_2 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      fold0_stage2_fork0_regs_3 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      fold0_stage1_fork0_regs_0 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      fold0_stage1_fork0_regs_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      fold0_stage1_fork0_regs_2 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
    end
    else begin	// <stdin>:348:11
      automatic logic fold0_stage1_fork0_transform0_leftBuffer_do_deq =
        fold0_stage1_fork0_transform0_leftBuffer_sink_ready
        & fold0_stage1_fork0_transform0_leftBuffer_sink_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      automatic logic fold0_stage1_fork0_leftBuffer_do_deq =
        fold0_stage1_fork0_leftBuffer_sink_ready
        & fold0_stage1_fork0_leftBuffer_sink_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      automatic logic fold0_stage1_fork0_rightBuffer_do_deq =
        fold0_stage1_fork0_rightBuffer_sink_ready
        & fold0_stage1_fork0_rightBuffer_sink_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      automatic logic fold0_stage1_fork0_leftBuffer_do_deq_1 =
        fold0_stage1_fork0_leftBuffer_sink_1_ready
        & fold0_stage1_fork0_leftBuffer_sink_1_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      if (_fold0_T)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_count <= fold0_count + 32'h1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:41:26, :45:24
      if (source_valid) begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:8:18
        if (fold0_stage0_transducerFirstLogic_state)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
          fold0_stage0_transducerFirstLogic_state <=
            (source_bits_last | ~fold0_stage0_ready)
            & fold0_stage0_transducerFirstLogic_state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:61:21, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
        else if (fold0_stage0_ready)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:61:21
          fold0_stage0_transducerFirstLogic_state <= source_bits_last;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
      end
      if (fold0_stage1_fork0_transform0_leftBuffer_do_enq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_transform0_leftBuffer_wrap <=
          fold0_stage1_fork0_transform0_leftBuffer_wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (fold0_stage1_fork0_transform0_leftBuffer_do_deq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_transform0_leftBuffer_wrap_1 <=
          fold0_stage1_fork0_transform0_leftBuffer_wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(fold0_stage1_fork0_transform0_leftBuffer_do_enq == fold0_stage1_fork0_transform0_leftBuffer_do_deq))	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_transform0_leftBuffer_maybe_full <=
          fold0_stage1_fork0_transform0_leftBuffer_do_enq;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      if (fold0_stage1_fork0_leftBuffer_do_enq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_leftBuffer_wrap <= fold0_stage1_fork0_leftBuffer_wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (fold0_stage1_fork0_leftBuffer_do_deq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_leftBuffer_wrap_1 <=
          fold0_stage1_fork0_leftBuffer_wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(fold0_stage1_fork0_leftBuffer_do_enq == fold0_stage1_fork0_leftBuffer_do_deq))	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_leftBuffer_maybe_full <= fold0_stage1_fork0_leftBuffer_do_enq;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      if (fold0_stage1_fork0_rightBuffer_do_enq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_rightBuffer_wrap <= fold0_stage1_fork0_rightBuffer_wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (fold0_stage1_fork0_rightBuffer_do_deq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_rightBuffer_wrap_1 <=
          fold0_stage1_fork0_rightBuffer_wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(fold0_stage1_fork0_rightBuffer_do_enq == fold0_stage1_fork0_rightBuffer_do_deq))	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_rightBuffer_maybe_full <=
          fold0_stage1_fork0_rightBuffer_do_enq;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      if (fold0_stage1_fork0_leftBuffer_do_enq_1)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_leftBuffer_wrap_2 <=
          fold0_stage1_fork0_leftBuffer_wrap_2 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (fold0_stage1_fork0_leftBuffer_do_deq_1)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_leftBuffer_wrap_3 <=
          fold0_stage1_fork0_leftBuffer_wrap_3 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(fold0_stage1_fork0_leftBuffer_do_enq_1 == fold0_stage1_fork0_leftBuffer_do_deq_1))	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
        fold0_stage1_fork0_leftBuffer_maybe_full_1 <=
          fold0_stage1_fork0_leftBuffer_do_enq_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      fold0_stage2_fork0_regs_0 <=
        fold0_stage2_fork0_ready_qual1_0
        & fold0_stage1_fork0_transform0_leftBuffer_sink_valid
        & ~fold0_stage1_fork0_transform0_leftBuffer_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, :73:{52,55}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
      fold0_stage2_fork0_regs_1 <=
        fold0_stage2_fork0_ready_qual1_1
        & fold0_stage1_fork0_transform0_leftBuffer_sink_valid
        & ~fold0_stage1_fork0_transform0_leftBuffer_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, :73:{52,55}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
      fold0_stage2_fork0_regs_2 <=
        fold0_stage2_fork0_ready_qual1_2
        & fold0_stage1_fork0_transform0_leftBuffer_sink_valid
        & ~fold0_stage1_fork0_transform0_leftBuffer_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, :73:{52,55}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
      fold0_stage2_fork0_regs_3 <=
        fold0_stage2_fork0_ready_qual1_3
        & fold0_stage1_fork0_transform0_leftBuffer_sink_valid
        & ~fold0_stage1_fork0_transform0_leftBuffer_sink_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, :73:{52,55}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
      fold0_stage1_fork0_regs_0 <=
        fold0_stage1_fork0_ready_qual1_0 & source_valid & ~fold0_stage0_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, :61:21, :73:{52,55}
      fold0_stage1_fork0_regs_1 <=
        fold0_stage1_fork0_ready_qual1_1 & source_valid & ~fold0_stage0_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, :61:21, :73:{52,55}
      fold0_stage1_fork0_regs_2 <=
        fold0_stage1_fork0_ready_qual1_2 & source_valid & ~fold0_stage0_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :59:20, :61:21, :73:{52,55}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      automatic logic [31:0] _RANDOM[0:1];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
        `INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
        end	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
        fold0_count = _RANDOM[1'h0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :41:26
        fold0_stage0_transducerFirstLogic_state = _RANDOM[1'h1][0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage1_fork0_transform0_leftBuffer_wrap = _RANDOM[1'h1][1];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_transform0_leftBuffer_wrap_1 = _RANDOM[1'h1][2];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_transform0_leftBuffer_maybe_full = _RANDOM[1'h1][3];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage1_fork0_leftBuffer_wrap = _RANDOM[1'h1][4];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_leftBuffer_wrap_1 = _RANDOM[1'h1][5];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_leftBuffer_maybe_full = _RANDOM[1'h1][6];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage1_fork0_rightBuffer_wrap = _RANDOM[1'h1][7];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_rightBuffer_wrap_1 = _RANDOM[1'h1][8];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_rightBuffer_maybe_full = _RANDOM[1'h1][9];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage1_fork0_leftBuffer_wrap_2 = _RANDOM[1'h1][10];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_leftBuffer_wrap_3 = _RANDOM[1'h1][11];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21, src/main/scala/chisel3/util/Counter.scala:61:40
        fold0_stage1_fork0_leftBuffer_maybe_full_1 = _RANDOM[1'h1][12];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage2_fork0_regs_0 = _RANDOM[1'h1][13];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage2_fork0_regs_1 = _RANDOM[1'h1][14];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage2_fork0_regs_2 = _RANDOM[1'h1][15];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage2_fork0_regs_3 = _RANDOM[1'h1][16];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage1_fork0_regs_0 = _RANDOM[1'h1][17];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage1_fork0_regs_1 = _RANDOM[1'h1][18];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
        fold0_stage1_fork0_regs_2 = _RANDOM[1'h1][19];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
      `FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(67)
  ) fold0_stage1_fork0_transform0_leftBuffer_ram (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .clock    (clock),
    .addrA    (fold0_stage1_fork0_transform0_leftBuffer_wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .writeEnA (fold0_stage1_fork0_transform0_leftBuffer_do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .dataInA
      ({fold0_stage1_fork0_transform0_leftBuffer_source_bits_operand,
        fold0_stage1_fork0_transform0_leftBuffer_source_bits_first,
        fold0_stage1_fork0_transform0_leftBuffer_source_bits_last,
        fold0_stage1_fork0_transform0_leftBuffer_source_bits_zero}),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .addrB    (fold0_stage1_fork0_transform0_leftBuffer_wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .dataOutB (_fold0_stage1_fork0_transform0_leftBuffer_ram_dataOutB)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(1)
  ) fold0_stage1_fork0_leftBuffer_ram (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .clock    (clock),
    .addrA    (fold0_stage1_fork0_leftBuffer_wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .writeEnA (fold0_stage1_fork0_leftBuffer_do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .dataInA  (fold0_stage1_fork0_leftBuffer_source_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .addrB    (fold0_stage1_fork0_leftBuffer_wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .dataOutB (fold0_stage1_fork0_leftBuffer_sink_bits)
  );
  wire [63:0] fold0_stage1_fork0_rightBuffer_sink_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  elasticMux fold0_stage1_fork0_mux (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
    .io_sources_0_ready (fold0_stage1_fork0_rightBuffer_sink_ready),
    .io_sources_0_valid (fold0_stage1_fork0_rightBuffer_sink_valid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_sources_0_bits  (fold0_stage1_fork0_rightBuffer_sink_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_sources_1_ready (/* unused */),
    .io_sources_1_valid (1'h1),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
    .io_sources_1_bits  (64'h0),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Connect.scala:48:15
    .io_sink_ready      (_fold0_stage2_fork0_demux_1_io_source_ready),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
    .io_sink_valid      (_fold0_stage1_fork0_mux_io_sink_valid),
    .io_sink_bits       (_fold0_stage1_fork0_mux_io_sink_bits),
    .io_select_ready    (fold0_stage1_fork0_leftBuffer_sink_ready),
    .io_select_valid    (fold0_stage1_fork0_leftBuffer_sink_valid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_select_bits     (fold0_stage1_fork0_leftBuffer_sink_bits)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  );
  wire [63:0] fold0_stage1_fork0_rightBuffer_source_bits;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(64)
  ) fold0_stage1_fork0_rightBuffer_ram (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .clock    (clock),
    .addrA    (fold0_stage1_fork0_rightBuffer_wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .writeEnA (fold0_stage1_fork0_rightBuffer_do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .dataInA  (fold0_stage1_fork0_rightBuffer_source_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .addrB    (fold0_stage1_fork0_rightBuffer_wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .dataOutB (fold0_stage1_fork0_rightBuffer_sink_bits)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(1)
  ) fold0_stage1_fork0_leftBuffer_ram_1 (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .clock    (clock),
    .addrA    (fold0_stage1_fork0_leftBuffer_wrap_2),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .writeEnA (fold0_stage1_fork0_leftBuffer_do_enq_1),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .dataInA  (fold0_stage1_fork0_leftBuffer_source_1_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .addrB    (fold0_stage1_fork0_leftBuffer_wrap_3),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .dataOutB (fold0_stage1_fork0_leftBuffer_sink_1_bits)
  );
  elasticDemux fold0_stage1_fork0_demux (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
    .io_source_ready  (_fold0_stage1_fork0_demux_io_source_ready),
    .io_source_valid  (_fold0_stage2_fork0_mux_io_sink_valid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
    .io_source_bits   (_fold0_stage2_fork0_mux_io_sink_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
    .io_sinks_0_ready (fold0_stage1_fork0_rightBuffer_source_ready),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_sinks_0_valid (fold0_stage1_fork0_rightBuffer_source_valid),
    .io_sinks_0_bits  (fold0_stage1_fork0_rightBuffer_source_bits),
    .io_sinks_1_ready (sink_ready),
    .io_sinks_1_valid (_fold0_stage1_fork0_demux_io_sinks_1_valid),
    .io_sinks_1_bits  (_fold0_stage1_fork0_demux_io_sinks_1_bits),
    .io_select_ready  (fold0_stage1_fork0_leftBuffer_sink_1_ready),
    .io_select_valid  (fold0_stage1_fork0_leftBuffer_sink_1_valid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_select_bits   (fold0_stage1_fork0_leftBuffer_sink_1_bits)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  );
  elasticDemux fold0_stage2_fork0_demux (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
    .io_source_ready  (_fold0_stage2_fork0_demux_io_source_ready),
    .io_source_valid
      (fold0_stage1_fork0_transform0_leftBuffer_sink_valid & ~fold0_stage2_fork0_regs_0),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :66:{36,39}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_source_bits   (fold0_stage1_fork0_transform0_leftBuffer_sink_bits_operand),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_sinks_0_ready (fold0_sinkA_ready),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_sinks_0_valid (fold0_sinkA_valid),
    .io_sinks_0_bits  (fold0_sinkA_bits),
    .io_sinks_1_ready (1'h1),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
    .io_sinks_1_valid (/* unused */),
    .io_sinks_1_bits  (/* unused */),
    .io_select_ready  (_fold0_stage2_fork0_demux_io_select_ready),
    .io_select_valid
      (fold0_stage1_fork0_transform0_leftBuffer_sink_valid & ~fold0_stage2_fork0_regs_1),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :66:{36,39}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_select_bits   (fold0_stage1_fork0_transform0_leftBuffer_sink_bits_zero)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  );
  elasticDemux fold0_stage2_fork0_demux_1 (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
    .io_source_ready  (_fold0_stage2_fork0_demux_1_io_source_ready),
    .io_source_valid  (_fold0_stage1_fork0_mux_io_sink_valid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
    .io_source_bits   (_fold0_stage1_fork0_mux_io_sink_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
    .io_sinks_0_ready (fold0_sinkB_ready),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_sinks_0_valid (fold0_sinkB_valid),
    .io_sinks_0_bits  (fold0_sinkB_bits),
    .io_sinks_1_ready (_fold0_stage2_fork0_mux_io_sources_1_ready),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
    .io_sinks_1_valid (_fold0_stage2_fork0_demux_1_io_sinks_1_valid),
    .io_sinks_1_bits  (_fold0_stage2_fork0_demux_1_io_sinks_1_bits),
    .io_select_ready  (_fold0_stage2_fork0_demux_1_io_select_ready),
    .io_select_valid
      (fold0_stage1_fork0_transform0_leftBuffer_sink_valid & ~fold0_stage2_fork0_regs_2),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :66:{36,39}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_select_bits   (fold0_stage1_fork0_transform0_leftBuffer_sink_bits_zero)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  );
  elasticMux fold0_stage2_fork0_mux (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Mux.scala:53:21
    .io_sources_0_ready (_fold0_stage2_fork0_mux_io_sources_0_ready),
    .io_sources_0_valid (fold0_join0_allValid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Join.scala:53:53
    .io_sources_0_bits  (fold0_sinkA_bits + fold0_sinkB_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21, :38:28
    .io_sources_1_ready (_fold0_stage2_fork0_mux_io_sources_1_ready),
    .io_sources_1_valid (_fold0_stage2_fork0_demux_1_io_sinks_1_valid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
    .io_sources_1_bits  (_fold0_stage2_fork0_demux_1_io_sinks_1_bits),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
    .io_sink_ready      (_fold0_stage1_fork0_demux_io_source_ready),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23
    .io_sink_valid      (_fold0_stage2_fork0_mux_io_sink_valid),
    .io_sink_bits       (_fold0_stage2_fork0_mux_io_sink_bits),
    .io_select_ready    (_fold0_stage2_fork0_mux_io_select_ready),
    .io_select_valid
      (fold0_stage1_fork0_transform0_leftBuffer_sink_valid & ~fold0_stage2_fork0_regs_3),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:55:23, :66:{36,39}, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
    .io_select_bits     (fold0_stage1_fork0_transform0_leftBuffer_sink_bits_zero)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:21:21
  );
  assign source_ready = source_valid & fold0_stage0_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Fork.scala:61:21, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :21:21
  assign sink_valid = _fold0_stage1_fork0_demux_io_sinks_1_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7
  assign sink_bits_result = _fold0_stage1_fork0_demux_io_sinks_1_bits[31:0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic/Demux.scala:50:23, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic/Fold.tb.scala:7:7, :50:18
endmodule

