// Generated by CIRCT firtool-1.138.0
module Null_Tbtop(
  input         clock,
                reset,
  input  [31:0] source_bits,
  input         source_valid,
  output        source_ready,
  output [31:0] sink_bits,
  output        sink_valid,
  input         sink_ready
);

  assign source_ready = 1'h1;
  assign sink_bits = 32'h0;
  assign sink_valid = 1'h0;
endmodule

