// Generated by CIRCT firtool-1.138.0
module SourceBufferedManyNaming_Tbtop(
  input         clock,
                reset,
  input  [15:0] sources_0_bits,
  input         sources_0_valid,
  output        sources_0_ready,
  input  [15:0] sources_1_bits,
  input         sources_1_valid,
  output        sources_1_ready,
  input  [15:0] sources_2_bits,
  input         sources_2_valid,
  output        sources_2_ready,
  input  [15:0] sources_3_bits,
  input         sources_3_valid,
  output        sources_3_ready,
  output [15:0] sinks_0_bits,
  output        sinks_0_valid,
  input         sinks_0_ready,
  output [15:0] sinks_1_bits,
  output        sinks_1_valid,
  input         sinks_1_ready,
  output [15:0] sinks_2_bits,
  output        sinks_2_valid,
  input         sinks_2_ready,
  output [15:0] sinks_3_bits,
  output        sinks_3_valid,
  input         sinks_3_ready
);

  wire [15:0] sourceBuffered0_0_bits;
  wire [15:0] sourceBuffered0_1_bits;
  wire [15:0] sourceBuffered0_2_bits;
  wire [15:0] sourceBuffered0_3_bits;
  wire        sourceBuffered0_0_ready = sinks_0_ready;
  wire        sourceBuffered0_1_ready = sinks_1_ready;
  wire        sourceBuffered0_2_ready = sinks_2_ready;
  wire        sourceBuffered0_3_ready = sinks_3_ready;
  reg         sourceBuffered0_3_queue0_enqPtr_value;
  reg         sourceBuffered0_3_queue0_deqPtr_value;
  reg         sourceBuffered0_3_queue0_maybeFull;
  wire        sourceBuffered0_3_queue0_ptrMatch =
    sourceBuffered0_3_queue0_enqPtr_value == sourceBuffered0_3_queue0_deqPtr_value;
  wire        sourceBuffered0_3_queue0_full =
    sourceBuffered0_3_queue0_ptrMatch & sourceBuffered0_3_queue0_maybeFull;
  wire        sourceBuffered0_3_queue0_doEnq =
    ~sourceBuffered0_3_queue0_full & sources_3_valid;
  wire        sourceBuffered0_3_valid =
    ~(sourceBuffered0_3_queue0_ptrMatch & ~sourceBuffered0_3_queue0_maybeFull);
  reg         sourceBuffered0_2_queue0_enqPtr_value;
  reg         sourceBuffered0_2_queue0_deqPtr_value;
  reg         sourceBuffered0_2_queue0_maybeFull;
  wire        sourceBuffered0_2_queue0_ptrMatch =
    sourceBuffered0_2_queue0_enqPtr_value == sourceBuffered0_2_queue0_deqPtr_value;
  wire        sourceBuffered0_2_queue0_full =
    sourceBuffered0_2_queue0_ptrMatch & sourceBuffered0_2_queue0_maybeFull;
  wire        sourceBuffered0_2_queue0_doEnq =
    ~sourceBuffered0_2_queue0_full & sources_2_valid;
  wire        sourceBuffered0_2_valid =
    ~(sourceBuffered0_2_queue0_ptrMatch & ~sourceBuffered0_2_queue0_maybeFull);
  reg         sourceBuffered0_1_queue0_enqPtr_value;
  reg         sourceBuffered0_1_queue0_deqPtr_value;
  reg         sourceBuffered0_1_queue0_maybeFull;
  wire        sourceBuffered0_1_queue0_ptrMatch =
    sourceBuffered0_1_queue0_enqPtr_value == sourceBuffered0_1_queue0_deqPtr_value;
  wire        sourceBuffered0_1_queue0_full =
    sourceBuffered0_1_queue0_ptrMatch & sourceBuffered0_1_queue0_maybeFull;
  wire        sourceBuffered0_1_queue0_doEnq =
    ~sourceBuffered0_1_queue0_full & sources_1_valid;
  wire        sourceBuffered0_1_valid =
    ~(sourceBuffered0_1_queue0_ptrMatch & ~sourceBuffered0_1_queue0_maybeFull);
  reg         sourceBuffered0_0_queue0_enqPtr_value;
  reg         sourceBuffered0_0_queue0_deqPtr_value;
  reg         sourceBuffered0_0_queue0_maybeFull;
  wire        sourceBuffered0_0_queue0_ptrMatch =
    sourceBuffered0_0_queue0_enqPtr_value == sourceBuffered0_0_queue0_deqPtr_value;
  wire        sourceBuffered0_0_queue0_full =
    sourceBuffered0_0_queue0_ptrMatch & sourceBuffered0_0_queue0_maybeFull;
  wire        sourceBuffered0_0_queue0_doEnq =
    ~sourceBuffered0_0_queue0_full & sources_0_valid;
  wire        sourceBuffered0_0_valid =
    ~(sourceBuffered0_0_queue0_ptrMatch & ~sourceBuffered0_0_queue0_maybeFull);
  always @(posedge clock) begin
    if (reset) begin
      sourceBuffered0_3_queue0_enqPtr_value <= 1'h0;
      sourceBuffered0_3_queue0_deqPtr_value <= 1'h0;
      sourceBuffered0_3_queue0_maybeFull <= 1'h0;
      sourceBuffered0_2_queue0_enqPtr_value <= 1'h0;
      sourceBuffered0_2_queue0_deqPtr_value <= 1'h0;
      sourceBuffered0_2_queue0_maybeFull <= 1'h0;
      sourceBuffered0_1_queue0_enqPtr_value <= 1'h0;
      sourceBuffered0_1_queue0_deqPtr_value <= 1'h0;
      sourceBuffered0_1_queue0_maybeFull <= 1'h0;
      sourceBuffered0_0_queue0_enqPtr_value <= 1'h0;
      sourceBuffered0_0_queue0_deqPtr_value <= 1'h0;
      sourceBuffered0_0_queue0_maybeFull <= 1'h0;
    end
    else begin
      automatic logic sourceBuffered0_0_queue0_doDeq =
        sourceBuffered0_0_ready & sourceBuffered0_0_valid;
      automatic logic sourceBuffered0_3_queue0_doDeq =
        sourceBuffered0_3_ready & sourceBuffered0_3_valid;
      automatic logic sourceBuffered0_1_queue0_doDeq =
        sourceBuffered0_1_ready & sourceBuffered0_1_valid;
      automatic logic sourceBuffered0_2_queue0_doDeq =
        sourceBuffered0_2_ready & sourceBuffered0_2_valid;
      if (sourceBuffered0_3_queue0_doEnq)
        sourceBuffered0_3_queue0_enqPtr_value <=
          sourceBuffered0_3_queue0_enqPtr_value - 1'h1;
      if (sourceBuffered0_3_queue0_doDeq)
        sourceBuffered0_3_queue0_deqPtr_value <=
          sourceBuffered0_3_queue0_deqPtr_value - 1'h1;
      if (sourceBuffered0_3_queue0_doEnq != sourceBuffered0_3_queue0_doDeq)
        sourceBuffered0_3_queue0_maybeFull <= sourceBuffered0_3_queue0_doEnq;
      if (sourceBuffered0_2_queue0_doEnq)
        sourceBuffered0_2_queue0_enqPtr_value <=
          sourceBuffered0_2_queue0_enqPtr_value - 1'h1;
      if (sourceBuffered0_2_queue0_doDeq)
        sourceBuffered0_2_queue0_deqPtr_value <=
          sourceBuffered0_2_queue0_deqPtr_value - 1'h1;
      if (sourceBuffered0_2_queue0_doEnq != sourceBuffered0_2_queue0_doDeq)
        sourceBuffered0_2_queue0_maybeFull <= sourceBuffered0_2_queue0_doEnq;
      if (sourceBuffered0_1_queue0_doEnq)
        sourceBuffered0_1_queue0_enqPtr_value <=
          sourceBuffered0_1_queue0_enqPtr_value - 1'h1;
      if (sourceBuffered0_1_queue0_doDeq)
        sourceBuffered0_1_queue0_deqPtr_value <=
          sourceBuffered0_1_queue0_deqPtr_value - 1'h1;
      if (sourceBuffered0_1_queue0_doEnq != sourceBuffered0_1_queue0_doDeq)
        sourceBuffered0_1_queue0_maybeFull <= sourceBuffered0_1_queue0_doEnq;
      if (sourceBuffered0_0_queue0_doEnq)
        sourceBuffered0_0_queue0_enqPtr_value <=
          sourceBuffered0_0_queue0_enqPtr_value - 1'h1;
      if (sourceBuffered0_0_queue0_doDeq)
        sourceBuffered0_0_queue0_deqPtr_value <=
          sourceBuffered0_0_queue0_deqPtr_value - 1'h1;
      if (sourceBuffered0_0_queue0_doEnq != sourceBuffered0_0_queue0_doDeq)
        sourceBuffered0_0_queue0_maybeFull <= sourceBuffered0_0_queue0_doEnq;
    end
  end // always @(posedge)
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(16)
  ) sourceBuffered0_3_queue0_ram (
    .clock    (clock),
    .addrA    (sourceBuffered0_3_queue0_enqPtr_value),
    .writeEnA (sourceBuffered0_3_queue0_doEnq),
    .dataInA  (sources_3_bits),
    .addrB    (sourceBuffered0_3_queue0_deqPtr_value),
    .dataOutB (sourceBuffered0_3_bits)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(16)
  ) sourceBuffered0_2_queue0_ram (
    .clock    (clock),
    .addrA    (sourceBuffered0_2_queue0_enqPtr_value),
    .writeEnA (sourceBuffered0_2_queue0_doEnq),
    .dataInA  (sources_2_bits),
    .addrB    (sourceBuffered0_2_queue0_deqPtr_value),
    .dataOutB (sourceBuffered0_2_bits)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(16)
  ) sourceBuffered0_1_queue0_ram (
    .clock    (clock),
    .addrA    (sourceBuffered0_1_queue0_enqPtr_value),
    .writeEnA (sourceBuffered0_1_queue0_doEnq),
    .dataInA  (sources_1_bits),
    .addrB    (sourceBuffered0_1_queue0_deqPtr_value),
    .dataOutB (sourceBuffered0_1_bits)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(16)
  ) sourceBuffered0_0_queue0_ram (
    .clock    (clock),
    .addrA    (sourceBuffered0_0_queue0_enqPtr_value),
    .writeEnA (sourceBuffered0_0_queue0_doEnq),
    .dataInA  (sources_0_bits),
    .addrB    (sourceBuffered0_0_queue0_deqPtr_value),
    .dataOutB (sourceBuffered0_0_bits)
  );
  assign sources_0_ready = ~sourceBuffered0_0_queue0_full;
  assign sources_1_ready = ~sourceBuffered0_1_queue0_full;
  assign sources_2_ready = ~sourceBuffered0_2_queue0_full;
  assign sources_3_ready = ~sourceBuffered0_3_queue0_full;
  assign sinks_0_bits = sourceBuffered0_0_bits;
  assign sinks_0_valid = sourceBuffered0_0_valid;
  assign sinks_1_bits = sourceBuffered0_1_bits;
  assign sinks_1_valid = sourceBuffered0_1_valid;
  assign sinks_2_bits = sourceBuffered0_2_bits;
  assign sinks_2_valid = sourceBuffered0_2_valid;
  assign sinks_3_bits = sourceBuffered0_3_bits;
  assign sinks_3_valid = sourceBuffered0_3_valid;
endmodule

