// Generated by CIRCT firtool-1.138.0
module elasticDemux(
  input  [31:0] io_source_bits_data,
                io_source_bits_repeat,
  input         io_source_valid,
  output        io_source_ready,
                io_sinks_0_valid,
  input         io_sinks_0_ready,
  output [31:0] io_sinks_1_bits_data,
  output        io_sinks_1_valid,
  input         io_sinks_1_ready,
  output [31:0] io_sinks_2_bits_data,
                io_sinks_2_bits_repeat,
  output        io_sinks_2_valid,
  input         io_sinks_2_ready,
  input  [1:0]  io_select_bits,
  input         io_select_valid,
  output        io_select_ready
);

  wire       valid = io_select_valid & io_source_valid;
  wire [3:0] _GEN =
    {{io_sinks_0_ready}, {io_sinks_2_ready}, {io_sinks_1_ready}, {io_sinks_0_ready}};
  wire       fire = valid & _GEN[io_select_bits];
  assign io_source_ready = fire;
  assign io_sinks_0_valid = valid & io_select_bits == 2'h0;
  assign io_sinks_1_bits_data = io_source_bits_data;
  assign io_sinks_1_valid = valid & io_select_bits == 2'h1;
  assign io_sinks_2_bits_data = io_source_bits_data;
  assign io_sinks_2_bits_repeat = io_source_bits_repeat;
  assign io_sinks_2_valid = valid & io_select_bits == 2'h2;
  assign io_select_ready = fire;
endmodule

module elasticMux(
  input         io_sources_0_valid,
  output        io_sources_0_ready,
  input  [31:0] io_sources_1_bits_data,
  input         io_sources_1_valid,
  output        io_sources_1_ready,
  input  [31:0] io_sources_2_bits_data,
  input         io_sources_2_bits_last,
                io_sources_2_valid,
  output        io_sources_2_ready,
  output [31:0] io_sink_bits_data,
  output        io_sink_bits_last,
                io_sink_valid,
  input         io_sink_ready,
  input  [1:0]  io_select_bits,
  input         io_select_valid,
  output        io_select_ready
);

  wire [0:0]       _GEN = '{1'h1};
  wire [0:0][31:0] _GEN_0 = '{32'hF0F0F0F};
  wire [3:0][31:0] _GEN_1 =
    {_GEN_0, {{io_sources_2_bits_data}, {io_sources_1_bits_data}, {32'hF0F0F0F}}};
  wire [3:0]       _GEN_2 = {_GEN, {{io_sources_2_bits_last}, {1'h1}, {1'h1}}};
  wire [3:0]       _GEN_3 =
    {{io_sources_0_valid},
     {io_sources_2_valid},
     {io_sources_1_valid},
     {io_sources_0_valid}};
  wire             valid = io_select_valid & _GEN_3[io_select_bits];
  wire             fire = valid & io_sink_ready;
  assign io_sources_0_ready = fire & io_select_bits == 2'h0;
  assign io_sources_1_ready = fire & io_select_bits == 2'h1;
  assign io_sources_2_ready = fire & io_select_bits == 2'h2;
  assign io_sink_bits_data = _GEN_1[io_select_bits];
  assign io_sink_bits_last = _GEN_2[io_select_bits];
  assign io_sink_valid = valid;
  assign io_select_ready = fire & _GEN_2[io_select_bits];
endmodule

module Switch_Tbtop(
  input         clock,
                reset,
  input  [1:0]  source_bits_tokenType,
  input  [31:0] source_bits_data,
                source_bits_repeat,
  input         source_valid,
  output        source_ready,
  output [31:0] sink_bits_data,
  output        sink_valid,
  input         sink_ready
);

  wire        wire0_bits_last;
  wire        wire0_valid;
  wire [31:0] wire0_bits_data;
  wire [1:0]  switch0_queueIndex_sink_bits;
  wire        switch0_queueIndex_source_ready;
  wire        _switch0_mux0_io_sources_0_ready;
  wire        _switch0_mux0_io_sources_1_ready;
  wire        _switch0_mux0_io_sources_2_ready;
  wire        _switch0_fork0_demux0_io_sinks_0_valid;
  wire [31:0] _switch0_fork0_demux0_io_sinks_1_bits_data;
  wire        _switch0_fork0_demux0_io_sinks_1_valid;
  wire [31:0] _switch0_fork0_demux0_io_sinks_2_bits_data;
  wire [31:0] _switch0_fork0_demux0_io_sinks_2_bits_repeat;
  wire        _switch0_fork0_demux0_io_sinks_2_valid;
  wire        wire0_ready = sink_ready;
  wire [1:0]  switch0_fork0_result_bits_tokenType = source_bits_tokenType;
  wire [31:0] switch0_fork0_result_bits_data = source_bits_data;
  wire [31:0] switch0_fork0_result_bits_repeat = source_bits_repeat;
  wire [1:0]  switch0_fork0_result_2_bits;
  wire        switch0_fork0_result_2_valid;
  wire        switch0_fork0_result_2_ready = switch0_queueIndex_source_ready;
  reg  [1:0]  switch0_queueIndex_enq_ptr_value;
  reg  [1:0]  switch0_queueIndex_deq_ptr_value;
  reg         switch0_queueIndex_maybe_full;
  wire        switch0_queueIndex_ptr_match =
    switch0_queueIndex_enq_ptr_value == switch0_queueIndex_deq_ptr_value;
  wire        switch0_queueIndex_source_valid;
  wire        switch0_queueIndex_do_enq =
    switch0_queueIndex_source_ready & switch0_queueIndex_source_valid;
  wire        switch0_queueIndex_sink_valid =
    ~(switch0_queueIndex_ptr_match & ~switch0_queueIndex_maybe_full);
  assign switch0_queueIndex_source_ready =
    ~(switch0_queueIndex_ptr_match & switch0_queueIndex_maybe_full);
  wire [1:0]  switch0_fork0_select =
    source_bits_tokenType == 2'h0 ? 2'h0 : source_bits_tokenType == 2'h1 ? 2'h1 : 2'h2;
  wire [1:0]  switch0_fork0_result_1_bits;
  assign switch0_fork0_result_1_bits = switch0_fork0_select;
  assign switch0_fork0_result_2_bits = switch0_fork0_select;
  assign switch0_queueIndex_source_valid = switch0_fork0_result_2_valid;
  wire [1:0]  switch0_queueIndex_source_bits = switch0_fork0_result_2_bits;
  reg         switch0_fork0_regs_0;
  reg         switch0_fork0_regs_1;
  reg         switch0_fork0_regs_2;
  wire        switch0_fork0_result_ready;
  wire        switch0_fork0_ready_qual1_0 =
    switch0_fork0_result_ready | switch0_fork0_regs_0;
  wire        switch0_fork0_result_1_ready;
  wire        switch0_fork0_ready_qual1_1 =
    switch0_fork0_result_1_ready | switch0_fork0_regs_1;
  wire        switch0_fork0_ready_qual1_2 =
    switch0_fork0_result_2_ready | switch0_fork0_regs_2;
  wire        source_ready_0 =
    switch0_fork0_ready_qual1_0 & switch0_fork0_ready_qual1_1
    & switch0_fork0_ready_qual1_2;
  wire        switch0_fork0_result_valid = source_valid & ~switch0_fork0_regs_0;
  wire        switch0_fork0_result_1_valid = source_valid & ~switch0_fork0_regs_1;
  assign switch0_fork0_result_2_valid = source_valid & ~switch0_fork0_regs_2;
  reg  [31:0] switch0_x2_repeat0_count_state;
  reg         switch0_x2_repeat0_count_valid;
  wire [31:0] _switch0_x2_repeat0_count_nextState_T =
    switch0_x2_repeat0_count_state + 32'h1;
  wire [32:0] _GEN = {1'h0, _switch0_fork0_demux0_io_sinks_2_bits_repeat};
  wire        _switch0_x2_repeat0_count_T_2 =
    {1'h0, _switch0_x2_repeat0_count_nextState_T} == _GEN + 33'h1;
  wire [32:0] _switch0_x2_repeat0_count_T_6 = _GEN + 33'h1;
  wire        _switch0_x2_repeat0_count_T_8 = _switch0_x2_repeat0_count_T_6 == 33'h1;
  wire        switch0_queueIndex_sink_ready;
  always @(posedge clock) begin
    automatic logic _GEN_0;
    _GEN_0 = ~(|_switch0_x2_repeat0_count_T_6) | _switch0_x2_repeat0_count_T_8;
    if (reset) begin
      switch0_queueIndex_enq_ptr_value <= 2'h0;
      switch0_queueIndex_deq_ptr_value <= 2'h0;
      switch0_queueIndex_maybe_full <= 1'h0;
      switch0_fork0_regs_0 <= 1'h0;
      switch0_fork0_regs_1 <= 1'h0;
      switch0_fork0_regs_2 <= 1'h0;
      switch0_x2_repeat0_count_valid <= 1'h0;
    end
    else begin
      automatic logic switch0_queueIndex_do_deq =
        switch0_queueIndex_sink_ready & switch0_queueIndex_sink_valid;
      if (switch0_queueIndex_do_enq)
        switch0_queueIndex_enq_ptr_value <=
          switch0_queueIndex_enq_ptr_value == 2'h2
            ? 2'h0
            : switch0_queueIndex_enq_ptr_value + 2'h1;
      if (switch0_queueIndex_do_deq)
        switch0_queueIndex_deq_ptr_value <=
          switch0_queueIndex_deq_ptr_value == 2'h2
            ? 2'h0
            : switch0_queueIndex_deq_ptr_value + 2'h1;
      if (switch0_queueIndex_do_enq != switch0_queueIndex_do_deq)
        switch0_queueIndex_maybe_full <= switch0_queueIndex_do_enq;
      switch0_fork0_regs_0 <=
        switch0_fork0_ready_qual1_0 & source_valid & ~source_ready_0;
      switch0_fork0_regs_1 <=
        switch0_fork0_ready_qual1_1 & source_valid & ~source_ready_0;
      switch0_fork0_regs_2 <=
        switch0_fork0_ready_qual1_2 & source_valid & ~source_ready_0;
      if (_switch0_fork0_demux0_io_sinks_2_valid) begin
        if (switch0_x2_repeat0_count_valid)
          switch0_x2_repeat0_count_valid <=
            ~(_switch0_x2_repeat0_count_T_2 & _switch0_mux0_io_sources_2_ready);
        else
          switch0_x2_repeat0_count_valid <= ~_GEN_0 & _switch0_mux0_io_sources_2_ready;
      end
    end
    if (_switch0_fork0_demux0_io_sinks_2_valid) begin
      if (switch0_x2_repeat0_count_valid) begin
        if (_switch0_mux0_io_sources_2_ready)
          switch0_x2_repeat0_count_state <=
            _switch0_x2_repeat0_count_T_2 ? 32'h0 : _switch0_x2_repeat0_count_nextState_T;
      end
      else if (_GEN_0 | ~_switch0_mux0_io_sources_2_ready) begin
      end
      else
        switch0_x2_repeat0_count_state <= 32'h1;
    end
  end // always @(posedge)
  chext_mem_1w1r #(
    .ADDR_WIDTH(2),
    .COUNT(3),
    .DATA_WIDTH(2)
  ) switch0_queueIndex_ram (
    .clock    (clock),
    .addrA    (switch0_queueIndex_enq_ptr_value),
    .writeEnA (switch0_queueIndex_do_enq),
    .dataInA  (switch0_queueIndex_source_bits),
    .addrB    (switch0_queueIndex_deq_ptr_value),
    .dataOutB (switch0_queueIndex_sink_bits)
  );
  elasticDemux switch0_fork0_demux0 (
    .io_source_bits_data    (switch0_fork0_result_bits_data),
    .io_source_bits_repeat  (switch0_fork0_result_bits_repeat),
    .io_source_valid        (switch0_fork0_result_valid),
    .io_source_ready        (switch0_fork0_result_ready),
    .io_sinks_0_valid       (_switch0_fork0_demux0_io_sinks_0_valid),
    .io_sinks_0_ready       (_switch0_mux0_io_sources_0_ready),
    .io_sinks_1_bits_data   (_switch0_fork0_demux0_io_sinks_1_bits_data),
    .io_sinks_1_valid       (_switch0_fork0_demux0_io_sinks_1_valid),
    .io_sinks_1_ready       (_switch0_mux0_io_sources_1_ready),
    .io_sinks_2_bits_data   (_switch0_fork0_demux0_io_sinks_2_bits_data),
    .io_sinks_2_bits_repeat (_switch0_fork0_demux0_io_sinks_2_bits_repeat),
    .io_sinks_2_valid       (_switch0_fork0_demux0_io_sinks_2_valid),
    .io_sinks_2_ready
      (_switch0_fork0_demux0_io_sinks_2_valid
       & (switch0_x2_repeat0_count_valid
            ? _switch0_x2_repeat0_count_T_2 & _switch0_mux0_io_sources_2_ready
            : ~(|_switch0_x2_repeat0_count_T_6) | _switch0_x2_repeat0_count_T_8
              & _switch0_mux0_io_sources_2_ready)),
    .io_select_bits         (switch0_fork0_result_1_bits),
    .io_select_valid        (switch0_fork0_result_1_valid),
    .io_select_ready        (switch0_fork0_result_1_ready)
  );
  elasticMux switch0_mux0 (
    .io_sources_0_valid     (_switch0_fork0_demux0_io_sinks_0_valid),
    .io_sources_0_ready     (_switch0_mux0_io_sources_0_ready),
    .io_sources_1_bits_data (_switch0_fork0_demux0_io_sinks_1_bits_data),
    .io_sources_1_valid     (_switch0_fork0_demux0_io_sinks_1_valid),
    .io_sources_1_ready     (_switch0_mux0_io_sources_1_ready),
    .io_sources_2_bits_data (_switch0_fork0_demux0_io_sinks_2_bits_data),
    .io_sources_2_bits_last
      (switch0_x2_repeat0_count_valid
         ? _switch0_x2_repeat0_count_T_2
         : _switch0_x2_repeat0_count_T_8),
    .io_sources_2_valid
      (_switch0_fork0_demux0_io_sinks_2_valid
       & (switch0_x2_repeat0_count_valid | (|_switch0_x2_repeat0_count_T_6))),
    .io_sources_2_ready     (_switch0_mux0_io_sources_2_ready),
    .io_sink_bits_data      (wire0_bits_data),
    .io_sink_bits_last      (wire0_bits_last),
    .io_sink_valid          (wire0_valid),
    .io_sink_ready          (wire0_ready),
    .io_select_bits         (switch0_queueIndex_sink_bits),
    .io_select_valid        (switch0_queueIndex_sink_valid),
    .io_select_ready        (switch0_queueIndex_sink_ready)
  );
  assign source_ready = source_ready_0;
  assign sink_bits_data = wire0_bits_data;
  assign sink_valid = wire0_valid;
endmodule

