// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module MaxPeriodFibonacciLFSR(	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
  input  clock,	// <stdin>:38:11, :104:11
         reset,	// <stdin>:39:11, :105:11
  output io_out_0,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_1,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_2,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_3	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
);

  reg state_0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_1;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_2;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_3;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  always @(posedge clock) begin	// <stdin>:38:11, :104:11
    if (reset) begin	// <stdin>:38:11, :104:11
      state_0 <= 1'h1;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_1 <= 1'h0;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_2 <= 1'h0;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_3 <= 1'h0;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
    end
    else begin	// <stdin>:38:11, :104:11
      state_0 <= state_3 ^ state_2;	// src/main/scala/chisel3/util/random/LFSR.scala:15:41, src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_1 <= state_0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_2 <= state_1;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_3 <= state_2;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
        state_0 = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_2 = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_3 = _RANDOM[/*Zero width*/ 1'b0][3];	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_0 = state_0;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_1 = state_1;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_2 = state_2;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_3 = state_3;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
endmodule

// VCS coverage exclude_file
module ram_2x42(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  input         R0_addr,
                R0_en,
                R0_clk,
  output [41:0] R0_data,
  input         W0_addr,
                W0_en,
                W0_clk,
  input  [41:0] W0_data
);

  reg [41:0] Memory[0:1];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  always @(posedge W0_clk) begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    if (W0_en & 1'h1)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      Memory[W0_addr] <= W0_data;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    reg [63:0] _RANDOM_MEM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    initial begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      `INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      `ifdef RANDOMIZE_MEM_INIT	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
          end	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
          Memory[i[0]] = _RANDOM_MEM[41:0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
        end	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 42'bx;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
endmodule

module chext_queue_2_Transducer_Tbtop_Anon(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
  input         clock,	// <stdin>:62:11
                reset,	// <stdin>:63:11
  output        source_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
  input         source_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
  input  [7:0]  source_bits_skip,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
  input  [31:0] source_bits_data,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
  input         source_bits_bad,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
                source_bits_stallForever,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
                sink_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
  output        sink_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
  output [7:0]  sink_bits_skip,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
  output [31:0] sink_bits_data,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
  output        sink_bits_bad,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
                sink_bits_stallForever	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
);

  wire [41:0] _ram_ext_R0_data;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  reg         wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg         maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27
  wire        ptr_match = wrap == wrap_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:74:33, src/main/scala/chisel3/util/Counter.scala:61:40
  wire        empty = ptr_match & ~maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, :74:33, :75:{25,28}
  wire        full = ptr_match & maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, :74:33, :76:24
  wire        do_enq = ~full & source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:76:24, :94:19, src/main/scala/chisel3/util/Decoupled.scala:51:35
  always @(posedge clock) begin	// <stdin>:62:11
    if (reset) begin	// <stdin>:62:11
      wrap <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
      wrap_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :73:27
    end
    else begin	// <stdin>:62:11
      automatic logic do_deq = sink_ready & ~empty;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:75:25, :93:17, src/main/scala/chisel3/util/Decoupled.scala:51:35
      if (do_enq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, :89:{15,27}, :90:16, src/main/scala/chisel3/util/Decoupled.scala:51:35
        maybe_full <= do_enq;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, src/main/scala/chisel3/util/Decoupled.scala:51:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    `ifdef FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      automatic logic [31:0] _RANDOM[0:0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `ifdef INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
        `INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :73:27, src/main/scala/chisel3/util/Counter.scala:61:40
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x42 ram_ext (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data
      ({source_bits_stallForever, source_bits_bad, source_bits_data, source_bits_skip})	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  );
  assign source_ready = ~full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :76:24, :94:19
  assign sink_valid = ~empty;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :75:25, :93:17
  assign sink_bits_skip = _ram_ext_R0_data[7:0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :70:81
  assign sink_bits_data = _ram_ext_R0_data[39:8];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :70:81
  assign sink_bits_bad = _ram_ext_R0_data[40];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :70:81
  assign sink_bits_stallForever = _ram_ext_R0_data[41];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :70:81
endmodule

// VCS coverage exclude_file
module ram_2x32(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  input         R0_addr,
                R0_en,
                R0_clk,
  output [31:0] R0_data,
  input         W0_addr,
                W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:1];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  always @(posedge W0_clk) begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    if (W0_en & 1'h1)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      Memory[W0_addr] <= W0_data;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    reg [31:0] _RANDOM_MEM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    initial begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      `INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      `ifdef RANDOMIZE_MEM_INIT	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM_MEM = `RANDOM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
          Memory[i[0]] = _RANDOM_MEM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
        end	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
endmodule

module chext_queue_2_UInt32(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
  input         clock,	// <stdin>:128:11
                reset,	// <stdin>:129:11
  output        source_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
  input         source_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
  input  [31:0] source_bits,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:67:18
  input         sink_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
  output        sink_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
  output [31:0] sink_bits	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:68:16
);

  reg  wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27
  wire ptr_match = wrap == wrap_1;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:74:33, src/main/scala/chisel3/util/Counter.scala:61:40
  wire empty = ptr_match & ~maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, :74:33, :75:{25,28}
  wire full = ptr_match & maybe_full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, :74:33, :76:24
  wire do_enq = ~full & source_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:76:24, :94:19, src/main/scala/chisel3/util/Decoupled.scala:51:35
  always @(posedge clock) begin	// <stdin>:128:11
    if (reset) begin	// <stdin>:128:11
      wrap <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
      wrap_1 <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :73:27
    end
    else begin	// <stdin>:128:11
      automatic logic do_deq = sink_ready & ~empty;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:75:25, :93:17, src/main/scala/chisel3/util/Decoupled.scala:51:35
      if (do_enq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, :89:{15,27}, :90:16, src/main/scala/chisel3/util/Decoupled.scala:51:35
        maybe_full <= do_enq;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:73:27, src/main/scala/chisel3/util/Decoupled.scala:51:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    `ifdef FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      automatic logic [31:0] _RANDOM[0:0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `ifdef INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
        `INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, src/main/scala/chisel3/util/Counter.scala:61:40
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :73:27, src/main/scala/chisel3/util/Counter.scala:61:40
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
      `FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x32 ram_ext (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:70:81
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7
    .R0_clk  (clock),
    .R0_data (sink_bits),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (source_bits)
  );
  assign source_ready = ~full;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :76:24, :94:19
  assign sink_valid = ~empty;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:53:7, :75:25, :93:17
endmodule

module Transducer_Tbtop(	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
  input         clock,	// <stdin>:170:11
                reset,	// <stdin>:171:11
  output        source_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:6:18
  input         source_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:6:18
  input  [7:0]  source_bits_skip,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:6:18
  input  [31:0] source_bits_data,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:6:18
  input         source_bits_bad,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:6:18
                source_bits_stallForever,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:6:18
                sink_ready,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:12:16
  output        sink_valid,	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:12:16
  output [31:0] sink_bits	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:12:16
);

  wire        _GEN;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29, :29:29
  wire        _GEN_0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:30:18, :33:24, :34:21
  wire        _stall1_stall0_x_queue_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
  wire        _stall1_rand_prng_io_out_0;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  wire        _stall1_rand_prng_io_out_1;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  wire        _stall1_rand_prng_io_out_2;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  wire        _stall1_rand_prng_io_out_3;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  wire        _stall0_stall0_x_queue_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
  wire        _stall0_stall0_x_queue_sink_valid;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
  wire [7:0]  _stall0_stall0_x_queue_sink_bits_skip;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
  wire [31:0] _stall0_stall0_x_queue_sink_bits_data;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
  wire        _stall0_stall0_x_queue_sink_bits_bad;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
  wire        _stall0_stall0_x_queue_sink_bits_stallForever;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
  wire        _stall0_rand_prng_io_out_0;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  wire        _stall0_rand_prng_io_out_1;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  wire        _stall0_rand_prng_io_out_2;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  wire        _stall0_rand_prng_io_out_3;	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
  reg  [7:0]  state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:21:24
  wire        _stall0_stall0_interface_valid_T =
    {_stall0_rand_prng_io_out_3,
     _stall0_rand_prng_io_out_2,
     _stall0_rand_prng_io_out_1,
     _stall0_rand_prng_io_out_0} < 4'h9;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:33:17, src/main/scala/chisel3/util/random/PRNG.scala:91:22, :95:17
  wire        _stall1_stall0_interface_valid_T =
    {_stall1_rand_prng_io_out_3,
     _stall1_rand_prng_io_out_2,
     _stall1_rand_prng_io_out_1,
     _stall1_rand_prng_io_out_0} < 4'h9;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:33:17, src/main/scala/chisel3/util/random/PRNG.scala:91:22, :95:17
  wire        sink__ready =
    _stall1_stall0_interface_valid_T & _stall1_stall0_x_queue_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:30:28, :33:17
  wire        _cond_WIRE_0 =
    _stall0_stall0_x_queue_sink_valid & ~_stall0_stall0_x_queue_sink_bits_stallForever
    & ~(|state);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :21:24, :26:29, :29:{20,29}
  wire        _cond_WIRE_1 =
    _stall0_stall0_x_queue_sink_valid & ~_stall0_stall0_x_queue_sink_bits_stallForever
    & ~(|state) & _stall0_stall0_x_queue_sink_bits_bad;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :21:24, :26:29, :29:{20,29}
  assign _GEN_0 = ~_stall0_stall0_x_queue_sink_bits_bad;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:30:18, :33:24, :34:21
  wire        _cond_WIRE_2 =
    _stall0_stall0_x_queue_sink_valid & ~_stall0_stall0_x_queue_sink_bits_stallForever
    & (|state);	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :21:24, :26:29, :29:{20,29}
  wire        _cond_WIRE_3 =
    _stall0_stall0_x_queue_sink_valid
    & ~(_stall0_stall0_x_queue_sink_bits_stallForever | ~(|state))
    & _stall0_stall0_x_queue_sink_bits_bad;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :21:24, :26:29, :29:{20,29}, :40:24
  assign _GEN = ~_stall0_stall0_x_queue_sink_bits_stallForever;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29, :29:29
  wire [3:0]  cond = {_cond_WIRE_3, _cond_WIRE_2, _cond_WIRE_1, _cond_WIRE_0};	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29
  wire        errorAtLeastTwoActions =
    _stall0_stall0_x_queue_sink_valid
    & (|(cond & {_cond_WIRE_3, _cond_WIRE_2, _cond_WIRE_1, _cond_WIRE_0} - 4'h1));	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29
  wire        errorNoAction = _stall0_stall0_x_queue_sink_valid & cond == 4'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
  `ifndef SYNTHESIS	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
    always @(posedge clock) begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
      if ((`PRINTF_COND_) & errorAtLeastTwoActions & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
        $fwrite(32'h80000002,
                "elastic.Transducer: at least two actions are taken in the same clock cycle!\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
      if ((`PRINTF_COND_) & errorAtLeastTwoActions & _cond_WIRE_0 & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala 30:18]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
      if ((`PRINTF_COND_) & errorAtLeastTwoActions & _cond_WIRE_1 & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'consume' @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala 34:21]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
      if ((`PRINTF_COND_) & errorAtLeastTwoActions & _cond_WIRE_2 & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'consume' @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala 37:19]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
      if ((`PRINTF_COND_) & errorAtLeastTwoActions & _cond_WIRE_3 & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :26:29
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'consume' @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala 41:21]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Transducer.scala:225:19, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
      if ((`PRINTF_COND_) & errorNoAction & ~reset)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
        $fwrite(32'h80000002,
                "elastic.Transducer: no action was taken! @[janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala 20:7]\n");	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// <stdin>:170:11
    if (reset)	// <stdin>:170:11
      state <= 8'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:21:24
    else if (~_stall0_stall0_x_queue_sink_valid
             | _stall0_stall0_x_queue_sink_bits_stallForever) begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :21:24, :26:29
    end
    else if (_stall0_stall0_x_queue_sink_bits_bad)	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
      state <= 8'h0;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:21:24
    else	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
      state <=
        (|state)
          ? state - 8'h1
          : sink__ready ? _stall0_stall0_x_queue_sink_bits_skip : state;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:30:28, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:21:24, :29:20, :30:{18,26}, :33:24, :34:29, :37:{27,36}, :40:24, :41:29
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
    `ifdef FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
      `FIRRTL_BEFORE_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
      automatic logic [31:0] _RANDOM[0:0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
      `ifdef INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
        `INIT_RANDOM_PROLOG_	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
        state = _RANDOM[/*Zero width*/ 1'b0][7:0];	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7, :21:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
      `FIRRTL_AFTER_INITIAL	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MaxPeriodFibonacciLFSR stall0_rand_prng (	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
    .clock    (clock),
    .reset    (reset),
    .io_out_0 (_stall0_rand_prng_io_out_0),
    .io_out_1 (_stall0_rand_prng_io_out_1),
    .io_out_2 (_stall0_rand_prng_io_out_2),
    .io_out_3 (_stall0_rand_prng_io_out_3)
  );
  chext_queue_2_Transducer_Tbtop_Anon stall0_stall0_x_queue (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
    .clock                    (clock),
    .reset                    (reset),
    .source_ready             (_stall0_stall0_x_queue_source_ready),
    .source_valid             (_stall0_stall0_interface_valid_T & source_valid),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:30:28, :33:17
    .source_bits_skip         (source_bits_skip),
    .source_bits_data         (source_bits_data),
    .source_bits_bad          (source_bits_bad),
    .source_bits_stallForever (source_bits_stallForever),
    .sink_ready
      (_stall0_stall0_x_queue_sink_valid & ~_stall0_stall0_x_queue_sink_bits_stallForever
       & ((|state) | _stall0_stall0_x_queue_sink_bits_bad | sink__ready)),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:30:28, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :21:24, :26:29, :29:{20,29}, :33:24, :40:24
    .sink_valid               (_stall0_stall0_x_queue_sink_valid),
    .sink_bits_skip           (_stall0_stall0_x_queue_sink_bits_skip),
    .sink_bits_data           (_stall0_stall0_x_queue_sink_bits_data),
    .sink_bits_bad            (_stall0_stall0_x_queue_sink_bits_bad),
    .sink_bits_stallForever   (_stall0_stall0_x_queue_sink_bits_stallForever)
  );
  MaxPeriodFibonacciLFSR stall1_rand_prng (	// src/main/scala/chisel3/util/random/PRNG.scala:91:22
    .clock    (clock),
    .reset    (reset),
    .io_out_0 (_stall1_rand_prng_io_out_0),
    .io_out_1 (_stall1_rand_prng_io_out_1),
    .io_out_2 (_stall1_rand_prng_io_out_2),
    .io_out_3 (_stall1_rand_prng_io_out_3)
  );
  chext_queue_2_UInt32 stall1_stall0_x_queue (	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
    .clock        (clock),
    .reset        (reset),
    .source_ready (_stall1_stall0_x_queue_source_ready),
    .source_valid
      (_stall1_stall0_interface_valid_T & _stall0_stall0_x_queue_sink_valid & _GEN
       & ~(|state) & _GEN_0),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:30:28, :33:17, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:20:7, :21:24, :26:29, :29:{20,29}, :30:18, :33:24, :34:21
    .source_bits  (_stall0_stall0_x_queue_sink_bits_data),	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13
    .sink_ready   (sink_ready),
    .sink_valid   (sink_valid),
    .sink_bits    (sink_bits)
  );
  assign source_ready =
    _stall0_stall0_interface_valid_T & _stall0_stall0_x_queue_source_ready;	// janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/Queue.scala:139:13, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/main/scala/chext/elastic2/RandomStall.scala:30:28, :33:17, janberq/repos/hdlstuff/hdlstuff/repos/chext/src/test/scala/chext/elastic2/Transducer.tb.scala:5:7
endmodule

