// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module chext_queue

// external module chext_queue

module ReadStream(	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
  input         clock,	// <stdin>:66:11
                reset,	// <stdin>:67:11
                m_axi_ar_ready,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:141:17
  output        m_axi_ar_valid,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:141:17
  output [31:0] m_axi_ar_bits_addr,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:141:17
  output [7:0]  m_axi_ar_bits_len,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:141:17
  output        m_axi_r_ready,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:141:17
  input         m_axi_r_valid,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:141:17
  input  [63:0] m_axi_r_bits_data,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:141:17
  output        sourceTask_ready,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:143:22
  input         sourceTask_valid,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:143:22
  input  [63:0] sourceTask_bits_address,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:143:22
                sourceTask_bits_length,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:143:22
  input         sinkData_ready,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:144:20
  output        sinkData_valid,	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:144:20
  output [63:0] sinkData_bits	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:144:20
);

  wire [7:0]   addressPhase_sinkBuffered__bits_len;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:57:13, :63:23, :64:29
  wire [31:0]  addressPhase_sinkBuffered__bits_addr;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:57:13, :63:23, :64:29
  wire         _addressPhase_sinkBuffered__x_queue_source_ready;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire [60:0]  _addressPhase_sinkBuffered__x_queue_sink_bits;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire         _filtering_arrival_sinkBuffered__x_queue_source_ready;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire         _filtering_arrival_sinkBuffered__x_queue_sink_valid;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire [127:0] _filtering_arrival_sinkBuffered__x_queue_sink_bits;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire         sourceTask_ready_0 =
    _filtering_arrival_sinkBuffered__x_queue_source_ready & sourceTask_valid;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  reg          addressPhase_rGenerating;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32
  reg  [63:0]  addressPhase_rRemaining;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31
  reg  [63:0]  addressPhase_rAddress;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:54:29
  wire         addressPhase_arrived =
    _addressPhase_sinkBuffered__x_queue_source_ready
    & _filtering_arrival_sinkBuffered__x_queue_sink_valid;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire         _addressPhase_T = addressPhase_rRemaining < 64'h101;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31, :65:29
  wire         _addressPhase_T_1 =
    _filtering_arrival_sinkBuffered__x_queue_sink_bits[63:0] < 64'h101;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, :230:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:65:29, :85:28
  assign addressPhase_sinkBuffered__bits_addr =
    addressPhase_arrived
      ? (addressPhase_rGenerating
           ? addressPhase_rAddress[31:0]
           : _filtering_arrival_sinkBuffered__x_queue_sink_bits[95:64])
      : 32'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32, :54:29, :57:{13,28}, :63:23, :64:29, :65:50, :70:24, :85:49, :90:24
  assign addressPhase_sinkBuffered__bits_len =
    addressPhase_arrived
      ? (addressPhase_rGenerating
           ? (_addressPhase_T ? addressPhase_rRemaining[7:0] - 8'h1 : 8'hFF)
           : _addressPhase_T_1
               ? _filtering_arrival_sinkBuffered__x_queue_sink_bits[7:0] - 8'h1
               : 8'hFF)
      : 8'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32, :53:31, :57:{13,28}, :63:23, :64:29, :65:{29,50}, :71:{23,37}, :80:23, :85:{28,49}, :91:{23,36}, :100:23
  always @(posedge clock) begin	// <stdin>:66:11
    if (reset) begin	// <stdin>:66:11
      addressPhase_rGenerating <= 1'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:42:18, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32
      addressPhase_rRemaining <= 64'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31
      addressPhase_rAddress <= 64'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31, :54:29
    end
    else if (addressPhase_arrived) begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47
      if (addressPhase_rGenerating) begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32
        addressPhase_rGenerating <= ~_addressPhase_T;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:35:18, :42:18, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32, :65:{29,50}, :66:27, :75:27
        if (_addressPhase_T) begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:65:29
          addressPhase_rRemaining <= 64'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31
          addressPhase_rAddress <= 64'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31, :54:29
        end
        else begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:65:29
          addressPhase_rRemaining <= addressPhase_rRemaining - 64'h100;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31, :76:40
          addressPhase_rAddress <= addressPhase_rAddress + 64'h800;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:54:29, :77:36
        end
      end
      else begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32
        addressPhase_rGenerating <= ~_addressPhase_T_1;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:35:18, :42:18, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32, :85:{28,49}, :86:27, :95:27
        addressPhase_rRemaining <=
          _addressPhase_T_1
            ? 64'h0
            : _filtering_arrival_sinkBuffered__x_queue_sink_bits[63:0] - 64'h100;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, :230:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31, :85:{28,49}, :87:26, :96:{26,39}
        addressPhase_rAddress <=
          _addressPhase_T_1
            ? 64'h0
            : _filtering_arrival_sinkBuffered__x_queue_sink_bits[127:64] + 64'h800;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, :230:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31, :54:29, :77:36, :85:{28,49}, :88:24, :97:{24,38}
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
      `FIRRTL_BEFORE_INITIAL	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
      automatic logic [31:0] _RANDOM[0:4];	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
      `ifdef INIT_RANDOM_PROLOG_	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
        `INIT_RANDOM_PROLOG_	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
        end	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
        addressPhase_rGenerating = _RANDOM[3'h0][0];	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32, :134:7
        addressPhase_rRemaining = {_RANDOM[3'h0][31:1], _RANDOM[3'h1], _RANDOM[3'h2][0]};	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32, :53:31, :134:7
        addressPhase_rAddress = {_RANDOM[3'h2][31:1], _RANDOM[3'h3], _RANDOM[3'h4][0]};	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:53:31, :54:29, :134:7
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
      `FIRRTL_AFTER_INITIAL	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  chext_queue #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(128),
    .FLOW(0),
    .PIPE(0),
    .USE_SYNCMEM(0)
  ) filtering_arrival_sinkBuffered__x_queue (	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
    .clock        (clock),
    .reset        (reset),
    .source_ready (_filtering_arrival_sinkBuffered__x_queue_source_ready),
    .source_valid (sourceTask_ready_0 & (|sourceTask_bits_length)),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47, :43:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:32:23, :33:{26,33}
    .source_bits  ({sourceTask_bits_address, sourceTask_bits_length}),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:226:25
    .sink_ready
      (addressPhase_arrived
       & (addressPhase_rGenerating ? _addressPhase_T : _addressPhase_T_1)),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47, :42:18, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:52:32, :63:23, :64:29, :65:{29,50}, :85:{28,49}
    .sink_valid   (_filtering_arrival_sinkBuffered__x_queue_sink_valid),
    .sink_bits    (_filtering_arrival_sinkBuffered__x_queue_sink_bits)
  );
  chext_queue #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(61),
    .FLOW(0),
    .PIPE(0),
    .USE_SYNCMEM(0)
  ) addressPhase_sinkBuffered__x_queue (	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
    .clock        (clock),
    .reset        (reset),
    .source_ready (_addressPhase_sinkBuffered__x_queue_source_ready),
    .source_valid (addressPhase_arrived),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47
    .source_bits
      ({addressPhase_sinkBuffered__bits_addr,
        addressPhase_sinkBuffered__bits_len,
        21'hD0000}),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:226:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:57:13, :63:23, :64:29
    .sink_ready   (m_axi_ar_ready),
    .sink_valid   (m_axi_ar_valid),
    .sink_bits    (_addressPhase_sinkBuffered__x_queue_sink_bits)
  );
  assign m_axi_ar_bits_addr = _addressPhase_sinkBuffered__x_queue_sink_bits[60:29];	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, :230:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
  assign m_axi_ar_bits_len = _addressPhase_sinkBuffered__x_queue_sink_bits[28:21];	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, :230:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
  assign m_axi_r_ready = sinkData_ready;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
  assign sourceTask_ready = sourceTask_ready_0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Arrival.scala:24:47, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
  assign sinkData_valid = m_axi_r_valid;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
  assign sinkData_bits = m_axi_r_bits_data;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/ip/stream/ReadStream.scala:134:7
endmodule

// external module chext_queue

module AxiTestSlave(	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
  input         clock,	// <stdin>:304:11
                reset,	// <stdin>:305:11
  output        s_axi_ar_ready,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:15:17
  input         s_axi_ar_valid,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:15:17
  input  [31:0] s_axi_ar_bits_addr,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:15:17
  input  [7:0]  s_axi_ar_bits_len,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:15:17
  input         s_axi_r_ready,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:15:17
  output        s_axi_r_valid,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:15:17
  output [63:0] s_axi_r_bits_data	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:15:17
);

  wire [31:0] _sinkBuffered__bits_data_T_2;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:29:39
  wire [31:0] _sinkBuffered__bits_data_index0_T_1;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:25:23
  wire [8:0]  _len_T;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:35:19
  wire [15:0] idx;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:58:22, :59:9, :61:9
  wire        last;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:26:29
  wire        _sinkBuffered__x_queue_source_ready;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire        _sinkBuffered__x_queue_sink_valid;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire [66:0] _sinkBuffered__x_queue_sink_bits;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire        _x_queue_source_ready;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  wire [66:0] _x_queue_sink_bits;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
  reg         generating_;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36
  reg  [15:0] idx_;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:20:29
  assign last = idx == {7'h0, _len_T} - 16'h1;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:26:{29,38}, :58:22, :59:9, :61:9, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:35:{9,19}
  wire        _GEN = s_axi_ar_valid & _sinkBuffered__x_queue_source_ready;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:33:21
  wire        _GEN_0 = _len_T == 9'h1;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:47:22, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:35:19
  assign idx = generating_ ? idx_ : 16'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :20:29, :58:22, :59:9, :61:9
  assign _len_T = {1'h0, s_axi_ar_bits_len} + 9'h1;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15, :35:19
  assign _sinkBuffered__bits_data_index0_T_1 = s_axi_ar_bits_addr + {15'h0, idx, 1'h0};	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:58:22, :59:9, :61:9, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15, :25:23
  assign _sinkBuffered__bits_data_T_2 = _sinkBuffered__bits_data_index0_T_1 + 32'h1;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:25:23, :29:39
  always @(posedge clock) begin	// <stdin>:304:11
    if (reset) begin	// <stdin>:304:11
      generating_ <= 1'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
      idx_ <= 16'h0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:20:29
    end
    else if (_GEN) begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:33:21
      if (generating_) begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36
        generating_ <= ~last & generating_;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :26:29, :35:18, :37:21
        idx_ <= idx_ + 16'h1;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:20:29, :43:20, :53:14
      end
      else begin	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36
        automatic logic _GEN_1 = ~(|_len_T) | _GEN_0;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :45:{16,25}, :47:{22,31}, :52:21, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:35:19
        generating_ <= ~_GEN_1 | generating_;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :45:25, :47:31, :52:21
        if (~_GEN_1)	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :45:25, :47:31, :52:21
          idx_ <= 16'h1;	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:20:29, :53:14
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
    `ifdef FIRRTL_BEFORE_INITIAL	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
      `FIRRTL_BEFORE_INITIAL	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
      automatic logic [31:0] _RANDOM[0:0];	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
      `ifdef INIT_RANDOM_PROLOG_	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
        `INIT_RANDOM_PROLOG_	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
        generating_ = _RANDOM[/*Zero width*/ 1'b0][0];	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
        idx_ = _RANDOM[/*Zero width*/ 1'b0][16:1];	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :20:29, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
      `FIRRTL_AFTER_INITIAL	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  chext_queue #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(67),
    .FLOW(0),
    .PIPE(0),
    .USE_SYNCMEM(0)
  ) x_queue (	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
    .clock        (clock),
    .reset        (reset),
    .source_ready (_x_queue_source_ready),
    .source_valid (_sinkBuffered__x_queue_sink_valid),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
    .source_bits  (_sinkBuffered__x_queue_sink_bits),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
    .sink_ready   (s_axi_r_ready),
    .sink_valid   (s_axi_r_valid),
    .sink_bits    (_x_queue_sink_bits)
  );
  chext_queue #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(67),
    .FLOW(0),
    .PIPE(0),
    .USE_SYNCMEM(0)
  ) sinkBuffered__x_queue (	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
    .clock        (clock),
    .reset        (reset),
    .source_ready (_sinkBuffered__x_queue_source_ready),
    .source_valid (_GEN & (generating_ | (|_len_T))),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :31:23, :33:{21,45}, :34:23, :42:27, :45:{16,25}, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:35:19
    .source_bits
      ({_sinkBuffered__bits_data_T_2, _sinkBuffered__bits_data_index0_T_1, 2'h0, last}),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:226:25, home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:26:29, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:25:23, :29:39, :37:24
    .sink_ready   (_x_queue_source_ready),	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15
    .sink_valid   (_sinkBuffered__x_queue_sink_valid),
    .sink_bits    (_sinkBuffered__x_queue_sink_bits)
  );
  assign s_axi_ar_ready = _GEN & (generating_ ? last : ~(|_len_T) | _GEN_0);	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Replicate.scala:19:36, :26:29, :30:16, :33:{21,45}, :34:23, :35:18, :45:{16,25}, :47:{22,31}, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15, :35:19, src/main/scala/chisel3/util/Decoupled.scala:76:20
  assign s_axi_r_bits_data = _x_queue_sink_bits[66:3];	// home/janberq/repos/hdlstuff/chext/src/main/scala/chext/elastic2/Queue.scala:218:15, :230:25, home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:14:15
endmodule

module ReadStreamTop1_1(	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:50:7
  input         clock,	// <stdin>:436:11
                reset,	// <stdin>:437:11
  output        sourceTask_ready,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:58:22
  input         sourceTask_valid,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:58:22
  input  [63:0] sourceTask_bits_address,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:58:22
                sourceTask_bits_length,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:58:22
  input         sinkData_ready,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:59:20
  output        sinkData_valid,	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:59:20
  output [63:0] sinkData_bits	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:59:20
);

  wire        _axiTestSlave_s_axi_ar_ready;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:56:36
  wire        _axiTestSlave_s_axi_r_valid;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:56:36
  wire [63:0] _axiTestSlave_s_axi_r_bits_data;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:56:36
  wire        _dut_m_axi_ar_valid;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
  wire [31:0] _dut_m_axi_ar_bits_addr;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
  wire [7:0]  _dut_m_axi_ar_bits_len;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
  wire        _dut_m_axi_r_ready;	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
  ReadStream dut (	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
    .clock                   (clock),
    .reset                   (reset),
    .m_axi_ar_ready          (_axiTestSlave_s_axi_ar_ready),	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:56:36
    .m_axi_ar_valid          (_dut_m_axi_ar_valid),
    .m_axi_ar_bits_addr      (_dut_m_axi_ar_bits_addr),
    .m_axi_ar_bits_len       (_dut_m_axi_ar_bits_len),
    .m_axi_r_ready           (_dut_m_axi_r_ready),
    .m_axi_r_valid           (_axiTestSlave_s_axi_r_valid),	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:56:36
    .m_axi_r_bits_data       (_axiTestSlave_s_axi_r_bits_data),	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:56:36
    .sourceTask_ready        (sourceTask_ready),
    .sourceTask_valid        (sourceTask_valid),
    .sourceTask_bits_address (sourceTask_bits_address),
    .sourceTask_bits_length  (sourceTask_bits_length),
    .sinkData_ready          (sinkData_ready),
    .sinkData_valid          (sinkData_valid),
    .sinkData_bits           (sinkData_bits)
  );
  AxiTestSlave axiTestSlave (	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:56:36
    .clock              (clock),
    .reset              (reset),
    .s_axi_ar_ready     (_axiTestSlave_s_axi_ar_ready),
    .s_axi_ar_valid     (_dut_m_axi_ar_valid),	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
    .s_axi_ar_bits_addr (_dut_m_axi_ar_bits_addr),	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
    .s_axi_ar_bits_len  (_dut_m_axi_ar_bits_len),	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
    .s_axi_r_ready      (_dut_m_axi_r_ready),	// home/janberq/repos/hdlstuff/chext/src/test/scala/chext/ip/stream/ReadStream.tb.scala:55:27
    .s_axi_r_valid      (_axiTestSlave_s_axi_r_valid),
    .s_axi_r_bits_data  (_axiTestSlave_s_axi_r_bits_data)
  );
endmodule

