// Generated by CIRCT firtool-1.138.0
module Buffer_Tbtop(
  input         clock,
                reset,
  input  [7:0]  readIn_req_bits,
  input         readIn_req_valid,
  output        readIn_req_ready,
  output [31:0] readIn_resp_bits,
  output        readIn_resp_valid,
  input         readIn_resp_ready,
  output [7:0]  readOut_req_bits,
  output        readOut_req_valid,
  input         readOut_req_ready,
  input  [31:0] readOut_resp_bits,
  input         readOut_resp_valid,
  output        readOut_resp_ready,
  input  [7:0]  writeIn_req_bits_addr,
  input  [31:0] writeIn_req_bits_data,
  input  [3:0]  writeIn_req_bits_strb,
  input         writeIn_req_valid,
  output        writeIn_req_ready,
                writeIn_resp_valid,
  input         writeIn_resp_ready,
  output [7:0]  writeOut_req_bits_addr,
  output [31:0] writeOut_req_bits_data,
  output [3:0]  writeOut_req_bits_strb,
  output        writeOut_req_valid,
  input         writeOut_req_ready,
                writeOut_resp_valid,
  output        writeOut_resp_ready
);

  wire [43:0] _masterBuffer0_reqBuffer0_queue0_ram_dataOutB;
  wire        slaveBuffer0_reqBuffer0_queueSink_ready = readOut_req_ready;
  wire [31:0] slaveBuffer0_respBuffer0_queueSource_bits = readOut_resp_bits;
  wire        slaveBuffer0_respBuffer0_queueSource_valid = readOut_resp_valid;
  wire        masterBuffer0_reqBuffer0_queueSink_ready = writeOut_req_ready;
  wire        masterBuffer0_respBuffer0_queueSource_valid = writeOut_resp_valid;
  wire [7:0]  masterBuffer0_result_req_bits_addr = writeIn_req_bits_addr;
  wire [31:0] masterBuffer0_result_req_bits_data = writeIn_req_bits_data;
  wire [3:0]  masterBuffer0_result_req_bits_strb = writeIn_req_bits_strb;
  wire        masterBuffer0_result_req_valid = writeIn_req_valid;
  wire        masterBuffer0_result_resp_ready = writeIn_resp_ready;
  reg         masterBuffer0_respBuffer0_queue0_maybeFull;
  wire        masterBuffer0_result_resp_valid =
    masterBuffer0_respBuffer0_queue0_maybeFull;
  wire        masterBuffer0_respBuffer0_queueSource_ready =
    ~masterBuffer0_respBuffer0_queue0_maybeFull;
  reg         masterBuffer0_reqBuffer0_queue0_enqPtr_value;
  reg         masterBuffer0_reqBuffer0_queue0_deqPtr_value;
  reg         masterBuffer0_reqBuffer0_queue0_maybeFull;
  wire        masterBuffer0_reqBuffer0_queue0_ptrMatch =
    masterBuffer0_reqBuffer0_queue0_enqPtr_value == masterBuffer0_reqBuffer0_queue0_deqPtr_value;
  wire        masterBuffer0_result_req_ready;
  wire        masterBuffer0_reqBuffer0_queue0_doEnq =
    masterBuffer0_result_req_ready & masterBuffer0_result_req_valid;
  wire        masterBuffer0_reqBuffer0_queueSink_valid =
    ~(masterBuffer0_reqBuffer0_queue0_ptrMatch
      & ~masterBuffer0_reqBuffer0_queue0_maybeFull);
  assign masterBuffer0_result_req_ready =
    ~(masterBuffer0_reqBuffer0_queue0_ptrMatch
      & masterBuffer0_reqBuffer0_queue0_maybeFull);
  wire [3:0]  masterBuffer0_reqBuffer0_queueSink_bits_strb =
    _masterBuffer0_reqBuffer0_queue0_ram_dataOutB[3:0];
  wire [31:0] masterBuffer0_reqBuffer0_queueSink_bits_data =
    _masterBuffer0_reqBuffer0_queue0_ram_dataOutB[35:4];
  wire        slaveBuffer0_result_resp_ready;
  wire [7:0]  masterBuffer0_reqBuffer0_queueSink_bits_addr =
    _masterBuffer0_reqBuffer0_queue0_ram_dataOutB[43:36];
  wire        slaveBuffer0_respBuffer0_queue0_doEnq =
    slaveBuffer0_result_resp_ready & slaveBuffer0_respBuffer0_queueSource_valid;
  reg         slaveBuffer0_respBuffer0_queue0_enqPtr_value;
  reg         slaveBuffer0_respBuffer0_queue0_deqPtr_value;
  reg         slaveBuffer0_respBuffer0_queue0_maybeFull;
  wire        slaveBuffer0_respBuffer0_queue0_ptrMatch =
    slaveBuffer0_respBuffer0_queue0_enqPtr_value == slaveBuffer0_respBuffer0_queue0_deqPtr_value;
  wire        slaveBuffer0_respBuffer0_queue0_empty =
    slaveBuffer0_respBuffer0_queue0_ptrMatch & ~slaveBuffer0_respBuffer0_queue0_maybeFull;
  assign slaveBuffer0_result_resp_ready =
    ~(slaveBuffer0_respBuffer0_queue0_ptrMatch
      & slaveBuffer0_respBuffer0_queue0_maybeFull);
  reg  [7:0]  slaveBuffer0_reqBuffer0_queue0_mem;
  wire [7:0]  slaveBuffer0_result_req_bits = slaveBuffer0_reqBuffer0_queue0_mem;
  reg         slaveBuffer0_reqBuffer0_queue0_maybeFull;
  wire        slaveBuffer0_result_req_valid = slaveBuffer0_reqBuffer0_queue0_maybeFull;
  always @(posedge clock) begin
    if (reset) begin
      masterBuffer0_respBuffer0_queue0_maybeFull <= 1'h0;
      masterBuffer0_reqBuffer0_queue0_enqPtr_value <= 1'h0;
      masterBuffer0_reqBuffer0_queue0_deqPtr_value <= 1'h0;
      masterBuffer0_reqBuffer0_queue0_maybeFull <= 1'h0;
      slaveBuffer0_respBuffer0_queue0_enqPtr_value <= 1'h0;
      slaveBuffer0_respBuffer0_queue0_deqPtr_value <= 1'h0;
      slaveBuffer0_respBuffer0_queue0_maybeFull <= 1'h0;
      slaveBuffer0_reqBuffer0_queue0_mem <= 8'h0;
      slaveBuffer0_reqBuffer0_queue0_maybeFull <= 1'h0;
    end
    else begin
      automatic logic masterBuffer0_respBuffer0_queue0_doEnq;
      automatic logic masterBuffer0_reqBuffer0_queue0_doDeq =
        masterBuffer0_reqBuffer0_queueSink_ready
        & masterBuffer0_reqBuffer0_queueSink_valid;
      automatic logic slaveBuffer0_respBuffer0_queue0_doDeq =
        readIn_resp_ready & ~slaveBuffer0_respBuffer0_queue0_empty;
      automatic logic slaveBuffer0_reqBuffer0_queue0_doEnq;
      masterBuffer0_respBuffer0_queue0_doEnq =
        masterBuffer0_respBuffer0_queueSource_ready
        & masterBuffer0_respBuffer0_queueSource_valid;
      slaveBuffer0_reqBuffer0_queue0_doEnq =
        ~slaveBuffer0_reqBuffer0_queue0_maybeFull & readIn_req_valid;
      if (masterBuffer0_respBuffer0_queue0_doEnq != (masterBuffer0_result_resp_ready
                                                     & masterBuffer0_result_resp_valid))
        masterBuffer0_respBuffer0_queue0_maybeFull <=
          masterBuffer0_respBuffer0_queue0_doEnq;
      if (masterBuffer0_reqBuffer0_queue0_doEnq)
        masterBuffer0_reqBuffer0_queue0_enqPtr_value <=
          masterBuffer0_reqBuffer0_queue0_enqPtr_value - 1'h1;
      if (masterBuffer0_reqBuffer0_queue0_doDeq)
        masterBuffer0_reqBuffer0_queue0_deqPtr_value <=
          masterBuffer0_reqBuffer0_queue0_deqPtr_value - 1'h1;
      if (masterBuffer0_reqBuffer0_queue0_doEnq != masterBuffer0_reqBuffer0_queue0_doDeq)
        masterBuffer0_reqBuffer0_queue0_maybeFull <=
          masterBuffer0_reqBuffer0_queue0_doEnq;
      if (slaveBuffer0_respBuffer0_queue0_doEnq)
        slaveBuffer0_respBuffer0_queue0_enqPtr_value <=
          slaveBuffer0_respBuffer0_queue0_enqPtr_value - 1'h1;
      if (slaveBuffer0_respBuffer0_queue0_doDeq)
        slaveBuffer0_respBuffer0_queue0_deqPtr_value <=
          slaveBuffer0_respBuffer0_queue0_deqPtr_value - 1'h1;
      if (slaveBuffer0_respBuffer0_queue0_doEnq != slaveBuffer0_respBuffer0_queue0_doDeq)
        slaveBuffer0_respBuffer0_queue0_maybeFull <=
          slaveBuffer0_respBuffer0_queue0_doEnq;
      if (slaveBuffer0_reqBuffer0_queue0_doEnq)
        slaveBuffer0_reqBuffer0_queue0_mem <= readIn_req_bits;
      if (slaveBuffer0_reqBuffer0_queue0_doEnq != (slaveBuffer0_reqBuffer0_queueSink_ready
                                                   & slaveBuffer0_result_req_valid))
        slaveBuffer0_reqBuffer0_queue0_maybeFull <= slaveBuffer0_reqBuffer0_queue0_doEnq;
    end
  end // always @(posedge)
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(44)
  ) masterBuffer0_reqBuffer0_queue0_ram (
    .clock    (clock),
    .addrA    (masterBuffer0_reqBuffer0_queue0_enqPtr_value),
    .writeEnA (masterBuffer0_reqBuffer0_queue0_doEnq),
    .dataInA
      ({masterBuffer0_result_req_bits_addr,
        masterBuffer0_result_req_bits_data,
        masterBuffer0_result_req_bits_strb}),
    .addrB    (masterBuffer0_reqBuffer0_queue0_deqPtr_value),
    .dataOutB (_masterBuffer0_reqBuffer0_queue0_ram_dataOutB)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(32)
  ) slaveBuffer0_respBuffer0_queue0_ram (
    .clock    (clock),
    .addrA    (slaveBuffer0_respBuffer0_queue0_enqPtr_value),
    .writeEnA (slaveBuffer0_respBuffer0_queue0_doEnq),
    .dataInA  (slaveBuffer0_respBuffer0_queueSource_bits),
    .addrB    (slaveBuffer0_respBuffer0_queue0_deqPtr_value),
    .dataOutB (readIn_resp_bits)
  );
  assign readIn_req_ready = ~slaveBuffer0_reqBuffer0_queue0_maybeFull;
  assign readIn_resp_valid = ~slaveBuffer0_respBuffer0_queue0_empty;
  assign readOut_req_bits = slaveBuffer0_result_req_bits;
  assign readOut_req_valid = slaveBuffer0_result_req_valid;
  assign readOut_resp_ready = slaveBuffer0_result_resp_ready;
  assign writeIn_req_ready = masterBuffer0_result_req_ready;
  assign writeIn_resp_valid = masterBuffer0_result_resp_valid;
  assign writeOut_req_bits_addr = masterBuffer0_reqBuffer0_queueSink_bits_addr;
  assign writeOut_req_bits_data = masterBuffer0_reqBuffer0_queueSink_bits_data;
  assign writeOut_req_bits_strb = masterBuffer0_reqBuffer0_queueSink_bits_strb;
  assign writeOut_req_valid = masterBuffer0_reqBuffer0_queueSink_valid;
  assign writeOut_resp_ready = masterBuffer0_respBuffer0_queueSource_ready;
endmodule

