// Generated by CIRCT firtool-1.138.0
module ConnectSeq_Tbtop(
  input         clock,
                reset,
  input  [7:0]  readIn_0_req_bits,
  input         readIn_0_req_valid,
  output        readIn_0_req_ready,
  output [31:0] readIn_0_resp_bits,
  output        readIn_0_resp_valid,
  input         readIn_0_resp_ready,
  input  [7:0]  readIn_1_req_bits,
  input         readIn_1_req_valid,
  output        readIn_1_req_ready,
  output [31:0] readIn_1_resp_bits,
  output        readIn_1_resp_valid,
  input         readIn_1_resp_ready,
  output [7:0]  readOut_0_req_bits,
  output        readOut_0_req_valid,
  input         readOut_0_req_ready,
  input  [31:0] readOut_0_resp_bits,
  input         readOut_0_resp_valid,
  output        readOut_0_resp_ready,
  output [7:0]  readOut_1_req_bits,
  output        readOut_1_req_valid,
  input         readOut_1_req_ready,
  input  [31:0] readOut_1_resp_bits,
  input         readOut_1_resp_valid,
  output        readOut_1_resp_ready,
  input  [7:0]  writeIn_0_req_bits_addr,
  input  [31:0] writeIn_0_req_bits_data,
  input  [3:0]  writeIn_0_req_bits_strb,
  input         writeIn_0_req_valid,
  output        writeIn_0_req_ready,
                writeIn_0_resp_valid,
  input         writeIn_0_resp_ready,
  input  [7:0]  writeIn_1_req_bits_addr,
  input  [31:0] writeIn_1_req_bits_data,
  input  [3:0]  writeIn_1_req_bits_strb,
  input         writeIn_1_req_valid,
  output        writeIn_1_req_ready,
                writeIn_1_resp_valid,
  input         writeIn_1_resp_ready,
  output [7:0]  writeOut_0_req_bits_addr,
  output [31:0] writeOut_0_req_bits_data,
  output [3:0]  writeOut_0_req_bits_strb,
  output        writeOut_0_req_valid,
  input         writeOut_0_req_ready,
                writeOut_0_resp_valid,
  output        writeOut_0_resp_ready,
  output [7:0]  writeOut_1_req_bits_addr,
  output [31:0] writeOut_1_req_bits_data,
  output [3:0]  writeOut_1_req_bits_strb,
  output        writeOut_1_req_valid,
  input         writeOut_1_req_ready,
                writeOut_1_resp_valid,
  output        writeOut_1_resp_ready
);

  assign readIn_0_req_ready = readOut_0_req_ready;
  assign readIn_0_resp_bits = readOut_0_resp_bits;
  assign readIn_0_resp_valid = readOut_0_resp_valid;
  assign readIn_1_req_ready = readOut_1_req_ready;
  assign readIn_1_resp_bits = readOut_1_resp_bits;
  assign readIn_1_resp_valid = readOut_1_resp_valid;
  assign readOut_0_req_bits = readIn_0_req_bits;
  assign readOut_0_req_valid = readIn_0_req_valid;
  assign readOut_0_resp_ready = readIn_0_resp_ready;
  assign readOut_1_req_bits = readIn_1_req_bits;
  assign readOut_1_req_valid = readIn_1_req_valid;
  assign readOut_1_resp_ready = readIn_1_resp_ready;
  assign writeIn_0_req_ready = writeOut_0_req_ready;
  assign writeIn_0_resp_valid = writeOut_0_resp_valid;
  assign writeIn_1_req_ready = writeOut_1_req_ready;
  assign writeIn_1_resp_valid = writeOut_1_resp_valid;
  assign writeOut_0_req_bits_addr = writeIn_0_req_bits_addr;
  assign writeOut_0_req_bits_data = writeIn_0_req_bits_data;
  assign writeOut_0_req_bits_strb = writeIn_0_req_bits_strb;
  assign writeOut_0_req_valid = writeIn_0_req_valid;
  assign writeOut_0_resp_ready = writeIn_0_resp_ready;
  assign writeOut_1_req_bits_addr = writeIn_1_req_bits_addr;
  assign writeOut_1_req_bits_data = writeIn_1_req_bits_data;
  assign writeOut_1_req_bits_strb = writeIn_1_req_bits_strb;
  assign writeOut_1_req_valid = writeIn_1_req_valid;
  assign writeOut_1_resp_ready = writeIn_1_resp_ready;
endmodule

