package chext.amba.axi4.tracking.properties

import chext.amba.axi4.tracking.{values => v}

/** Standard AXI property-key catalog inherited by the `properties` package object. */
trait Keys {
  val MasterReadBurstShape: Key[v.BurstShape] =
    Key(
      Role.Master,
      Access.Read,
      ValueType.BurstShape,
      "read_burstShape",
      "Burst shapes the master may generate for reads."
    )

  val MasterWriteBurstShape: Key[v.BurstShape] =
    Key(
      Role.Master,
      Access.Write,
      ValueType.BurstShape,
      "write_burstShape",
      "Burst shapes the master may generate for writes."
    )

  val MasterReadThreadMode: Key[v.ThreadMode] =
    Key(
      Role.Master,
      Access.Read,
      ValueType.ThreadMode,
      "read_threadMode",
      "ID relationship among the master's outstanding read transactions."
    )

  val MasterWriteThreadMode: Key[v.ThreadMode] =
    Key(
      Role.Master,
      Access.Write,
      ValueType.ThreadMode,
      "write_threadMode",
      "ID relationship among the master's outstanding write transactions."
    )

  val MasterReadTrafficProfile: Key[v.TrafficProfile] =
    Key(
      Role.Master,
      Access.Read,
      ValueType.TrafficProfile,
      "read_trafficProfile",
      "Concurrency and latency of read traffic generated by the master."
    )

  val MasterWriteTrafficProfile: Key[v.TrafficProfile] =
    Key(
      Role.Master,
      Access.Write,
      ValueType.TrafficProfile,
      "write_trafficProfile",
      "Concurrency and latency of write traffic generated by the master."
    )

  val SlaveMemoryMap: Key[v.MemoryMap] =
    Key(
      Role.Slave,
      Access.None,
      ValueType.MemoryMap,
      "memoryMap",
      "Memory map provided by the slave."
    )

  val SlaveReadBurstShape: Key[v.BurstShape] =
    Key(
      Role.Slave,
      Access.Read,
      ValueType.BurstShape,
      "read_burstShape",
      "Burst shapes the slave accepts for reads."
    )

  val SlaveWriteBurstShape: Key[v.BurstShape] =
    Key(
      Role.Slave,
      Access.Write,
      ValueType.BurstShape,
      "write_burstShape",
      "Burst shapes the slave accepts for writes."
    )

  val SlaveReadThreadMode: Key[v.ThreadMode] =
    Key(
      Role.Slave,
      Access.Read,
      ValueType.ThreadMode,
      "read_threadMode",
      "ID relationship among read transactions accepted by the slave."
    )

  val SlaveWriteThreadMode: Key[v.ThreadMode] =
    Key(
      Role.Slave,
      Access.Write,
      ValueType.ThreadMode,
      "write_threadMode",
      "ID relationship among write transactions accepted by the slave."
    )

  val SlaveReadTrafficProfile: Key[v.TrafficProfile] =
    Key(
      Role.Slave,
      Access.Read,
      ValueType.TrafficProfile,
      "read_trafficProfile",
      "Concurrency and latency of read traffic accepted by the slave."
    )

  val SlaveWriteTrafficProfile: Key[v.TrafficProfile] =
    Key(
      Role.Slave,
      Access.Write,
      ValueType.TrafficProfile,
      "write_trafficProfile",
      "Concurrency and latency of write traffic accepted by the slave."
    )

  val KnownKeys: Seq[Key[_]] =
    Seq(
      MasterReadBurstShape,
      MasterWriteBurstShape,
      MasterReadThreadMode,
      MasterWriteThreadMode,
      MasterReadTrafficProfile,
      MasterWriteTrafficProfile,
      SlaveMemoryMap,
      SlaveReadBurstShape,
      SlaveWriteBurstShape,
      SlaveReadThreadMode,
      SlaveWriteThreadMode,
      SlaveReadTrafficProfile,
      SlaveWriteTrafficProfile
    )
}
