package chext.amba.axi4.tracking.properties

import chext.amba.axi4.tracking.{
  MasterReadProperty,
  MasterWriteProperty,
  PropertyKey,
  ReadProperty,
  WriteProperty
}
import chext.amba.axi4.tracking.values.{BurstShape, ThreadMode, TrafficProfile}

object Master extends Iterable[PropertyKey[_]] {
  case object ReadBurstShape
      extends MasterReadProperty[BurstShape](
        "read_burstShape",
        "Burst shapes the master may generate for reads."
      )

  case object WriteBurstShape
      extends MasterWriteProperty[BurstShape](
        "write_burstShape",
        "Burst shapes the master may generate for writes."
      )

  case object ReadThreadMode
      extends MasterReadProperty[ThreadMode](
        "read_threadMode",
        "ID relationship among the master's outstanding read transactions."
      )

  case object WriteThreadMode
      extends MasterWriteProperty[ThreadMode](
        "write_threadMode",
        "ID relationship among the master's outstanding write transactions."
      )

  case object ReadTrafficProfile
      extends MasterReadProperty[TrafficProfile](
        "read_trafficProfile",
        "Concurrency and latency of read traffic generated by the master."
      )

  case object WriteTrafficProfile
      extends MasterWriteProperty[TrafficProfile](
        "write_trafficProfile",
        "Concurrency and latency of write traffic generated by the master."
      )

  val all: Seq[PropertyKey[_]] = Seq(
    ReadBurstShape,
    WriteBurstShape,
    ReadThreadMode,
    WriteThreadMode,
    ReadTrafficProfile,
    WriteTrafficProfile
  )

  val readProperties: Set[PropertyKey[_]] =
    all.collect { case key @ ReadProperty() => key }.toSet

  val writeProperties: Set[PropertyKey[_]] =
    all.collect { case key @ WriteProperty() => key }.toSet

  def iterator: Iterator[PropertyKey[_]] = all.iterator
}
