package chext.amba.axi4.tracking.properties

import chext.amba.axi4.tracking.{MasterPropertyKey, PropertyKey}

object Master extends Iterable[PropertyKey[_]] {
  case object ReadOutstandingTransactions
      extends MasterPropertyKey[Int](
        "read_outstandingTransactions",
        "Maximum number of read transactions the master may issue."
      )

  case object WriteOutstandingTransactions
      extends MasterPropertyKey[Int](
        "write_outstandingTransactions",
        "Maximum number of write transactions the master may issue."
      )

  case object ReadThreads
      extends MasterPropertyKey[Int](
        "read_threads",
        "Maximum number of read threads the master may generate."
      )

  case object WriteThreads
      extends MasterPropertyKey[Int](
        "write_threads",
        "Maximum number of write threads the master may generate."
      )

  case object ReadBurstBeats
      extends MasterPropertyKey[Int](
        "read_burstBeats",
        "Maximum read burst length in beats generated by the master."
      )

  case object WriteBurstBeats
      extends MasterPropertyKey[Int](
        "write_burstBeats",
        "Maximum write burst length in beats generated by the master."
      )

  case object ReadBurstNarrow
      extends MasterPropertyKey[Boolean](
        "read_burstNarrow",
        "Whether the master may generate narrow read bursts."
      )

  case object WriteBurstNarrow
      extends MasterPropertyKey[Boolean](
        "write_burstNarrow",
        "Whether the master may generate narrow write bursts."
      )

  case object ReadBurstTypes
      extends MasterPropertyKey[Set[Int]](
        "read_burstTypes",
        "AXI burst types the master may generate for reads."
      )

  case object WriteBurstTypes
      extends MasterPropertyKey[Set[Int]](
        "write_burstTypes",
        "AXI burst types the master may generate for writes."
      )

  case object ReadBurstSizes
      extends MasterPropertyKey[Set[Int]](
        "read_burstSizes",
        "AXI transfer sizes the master may generate for reads."
      )

  case object WriteBurstSizes
      extends MasterPropertyKey[Set[Int]](
        "write_burstSizes",
        "AXI transfer sizes the master may generate for writes."
      )

  val all: Seq[PropertyKey[_]] = Seq(
    ReadOutstandingTransactions,
    WriteOutstandingTransactions,
    ReadThreads,
    WriteThreads,
    ReadBurstBeats,
    WriteBurstBeats,
    ReadBurstNarrow,
    WriteBurstNarrow,
    ReadBurstTypes,
    WriteBurstTypes,
    ReadBurstSizes,
    WriteBurstSizes
  )

  def iterator: Iterator[PropertyKey[_]] = all.iterator
}
