package chext.amba.axi4.tracking.properties

import chext.amba.axi4.tracking.{
  MasterReadProperty,
  MasterWriteProperty,
  PropertyKey
}

object Master extends Iterable[PropertyKey[_]] {
  case object ReadOutstandingTransactions
      extends MasterReadProperty[Int](
        "read_outstandingTransactions",
        "Maximum number of read transactions the master may issue."
      )

  case object WriteOutstandingTransactions
      extends MasterWriteProperty[Int](
        "write_outstandingTransactions",
        "Maximum number of write transactions the master may issue."
      )

  case object ReadThreads
      extends MasterReadProperty[Int](
        "read_threads",
        "Maximum number of read threads the master may generate."
      )

  case object WriteThreads
      extends MasterWriteProperty[Int](
        "write_threads",
        "Maximum number of write threads the master may generate."
      )

  case object ReadBurstBeats
      extends MasterReadProperty[Int](
        "read_burstBeats",
        "Maximum read burst length in beats generated by the master."
      )

  case object WriteBurstBeats
      extends MasterWriteProperty[Int](
        "write_burstBeats",
        "Maximum write burst length in beats generated by the master."
      )

  case object ReadBurstNarrow
      extends MasterReadProperty[Boolean](
        "read_burstNarrow",
        "Whether the master may generate narrow read bursts."
      )

  case object WriteBurstNarrow
      extends MasterWriteProperty[Boolean](
        "write_burstNarrow",
        "Whether the master may generate narrow write bursts."
      )

  case object ReadBurstTypes
      extends MasterReadProperty[Set[Int]](
        "read_burstTypes",
        "AXI burst types the master may generate for reads."
      )

  case object WriteBurstTypes
      extends MasterWriteProperty[Set[Int]](
        "write_burstTypes",
        "AXI burst types the master may generate for writes."
      )

  case object ReadBurstSizes
      extends MasterReadProperty[Set[Int]](
        "read_burstSizes",
        "AXI transfer sizes the master may generate for reads."
      )

  case object WriteBurstSizes
      extends MasterWriteProperty[Set[Int]](
        "write_burstSizes",
        "AXI transfer sizes the master may generate for writes."
      )

  /** All standard properties associated with read traffic. */
  val readProperties: Set[PropertyKey[_]] = Set(
    ReadOutstandingTransactions,
    ReadThreads,
    ReadBurstBeats,
    ReadBurstNarrow,
    ReadBurstTypes,
    ReadBurstSizes
  )

  /** All standard properties associated with write traffic. */
  val writeProperties: Set[PropertyKey[_]] = Set(
    WriteOutstandingTransactions,
    WriteThreads,
    WriteBurstBeats,
    WriteBurstNarrow,
    WriteBurstTypes,
    WriteBurstSizes
  )

  /** Properties that describe the shape of traffic generated by a master. */
  val shapeProperties: Set[PropertyKey[_]] = Set(
    ReadBurstBeats,
    WriteBurstBeats,
    ReadBurstNarrow,
    WriteBurstNarrow,
    ReadBurstTypes,
    WriteBurstTypes,
    ReadBurstSizes,
    WriteBurstSizes
  )

  /** Boolean extractor for keys in [[shapeProperties]]. */
  object ShapeProperty {
    def unapply(key: PropertyKey[_]): Boolean =
      shapeProperties.contains(key)
  }

  val all: Seq[PropertyKey[_]] = Seq(
    ReadOutstandingTransactions,
    WriteOutstandingTransactions,
    ReadThreads,
    WriteThreads,
    ReadBurstBeats,
    WriteBurstBeats,
    ReadBurstNarrow,
    WriteBurstNarrow,
    ReadBurstTypes,
    WriteBurstTypes,
    ReadBurstSizes,
    WriteBurstSizes
  )

  def iterator: Iterator[PropertyKey[_]] = all.iterator
}
