// Generated by CIRCT firtool-1.138.0
// VCS coverage exclude_file
module sram_sram_256x67(
  input  [7:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [66:0] R0_data,
  input  [7:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [66:0] W0_data
);

  reg [66:0] Memory[0:255];
  reg        _R0_en_d0;
  reg [7:0]  _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 67'bx;
endmodule

module SyncWriteElasticReadMemory(
  input         clock,
                reset,
                io_wrEn,
  input  [7:0]  io_wrAddr,
  input  [63:0] io_wrData_data,
  input  [1:0]  io_wrData_resp,
  input         io_wrData_last,
  input  [7:0]  io_rdReq_bits,
  input         io_rdReq_valid,
  output        io_rdReq_ready,
  output [63:0] io_rdResp_bits_data,
  output [1:0]  io_rdResp_bits_resp,
  output        io_rdResp_bits_last,
                io_rdResp_valid,
  input         io_rdResp_ready
);

  wire [66:0] _queueRd_ram_dataOutB;
  wire [66:0] _sram_sram_ext_R0_data;
  wire        queueRd_sink_ready = io_rdResp_ready;
  wire [63:0] queueRd_source_bits_data = _sram_sram_ext_R0_data[66:3];
  wire [1:0]  queueRd_source_bits_resp = _sram_sram_ext_R0_data[2:1];
  wire        queueRd_source_bits_last = _sram_sram_ext_R0_data[0];
  reg  [2:0]  rdCounter_rCounter;
  wire        rdCounter_empty = rdCounter_rCounter == 3'h0;
  wire        rdCounter_full_ = rdCounter_rCounter == 3'h4;
  wire        rdCounter_incEn = ~rdCounter_full_ & io_rdReq_valid;
  reg         r;
  wire        queueRd_source_valid = r;
  wire        queueRd_sink_valid;
  wire        rdCounter_decEn = io_rdResp_ready & queueRd_sink_valid;
  reg  [1:0]  queueRd_enqPtr_value;
  reg  [1:0]  queueRd_deqPtr_value;
  reg         queueRd_maybeFull;
  wire        queueRd_ptrMatch = queueRd_enqPtr_value == queueRd_deqPtr_value;
  wire        queueRd_source_ready;
  wire        queueRd_doEnq = queueRd_source_ready & queueRd_source_valid;
  assign queueRd_sink_valid = ~(queueRd_ptrMatch & ~queueRd_maybeFull);
  assign queueRd_source_ready = ~(queueRd_ptrMatch & queueRd_maybeFull);
  wire        queueRd_sink_bits_last = _queueRd_ram_dataOutB[0];
  wire [1:0]  queueRd_sink_bits_resp = _queueRd_ram_dataOutB[2:1];
  wire [63:0] queueRd_sink_bits_data = _queueRd_ram_dataOutB[66:3];
  always @(posedge clock) begin
    if (reset) begin
      rdCounter_rCounter <= 3'h0;
      queueRd_enqPtr_value <= 2'h0;
      queueRd_deqPtr_value <= 2'h0;
      queueRd_maybeFull <= 1'h0;
    end
    else begin
      automatic logic queueRd_doDeq = queueRd_sink_ready & queueRd_sink_valid;
      if (~(rdCounter_incEn & rdCounter_decEn)) begin
        if (rdCounter_incEn)
          rdCounter_rCounter <= rdCounter_rCounter + 3'h1;
        else if (rdCounter_decEn)
          rdCounter_rCounter <= rdCounter_rCounter - 3'h1;
      end
      if (queueRd_doEnq)
        queueRd_enqPtr_value <= queueRd_enqPtr_value + 2'h1;
      if (queueRd_doDeq)
        queueRd_deqPtr_value <= queueRd_deqPtr_value + 2'h1;
      if (queueRd_doEnq != queueRd_doDeq)
        queueRd_maybeFull <= queueRd_doEnq;
    end
    r <= rdCounter_incEn;
  end // always @(posedge)
  sram_sram_256x67 sram_sram_ext (
    .R0_addr (io_rdReq_bits),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_sram_sram_ext_R0_data),
    .W0_addr (io_wrAddr),
    .W0_en   (io_wrEn),
    .W0_clk  (clock),
    .W0_data ({io_wrData_data, io_wrData_resp, io_wrData_last})
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(2),
    .COUNT(4),
    .DATA_WIDTH(67)
  ) queueRd_ram (
    .clock    (clock),
    .addrA    (queueRd_enqPtr_value),
    .writeEnA (queueRd_doEnq),
    .dataInA
      ({queueRd_source_bits_data, queueRd_source_bits_resp, queueRd_source_bits_last}),
    .addrB    (queueRd_deqPtr_value),
    .dataOutB (_queueRd_ram_dataOutB)
  );
  assign io_rdReq_ready = ~rdCounter_full_;
  assign io_rdResp_bits_data = queueRd_sink_bits_data;
  assign io_rdResp_bits_resp = queueRd_sink_bits_resp;
  assign io_rdResp_bits_last = queueRd_sink_bits_last;
  assign io_rdResp_valid = queueRd_sink_valid;
endmodule

// VCS coverage exclude_file
module sram_sram_64x34(
  input  [5:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [33:0] R0_data,
  input  [5:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [33:0] W0_data
);

  reg [33:0] Memory[0:63];
  reg        _R0_en_d0;
  reg [5:0]  _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 34'bx;
endmodule

module SyncWriteElasticReadMemory_1(
  input         clock,
                reset,
                io_wrEn,
  input  [5:0]  io_wrAddr,
  input  [1:0]  io_wrData_resp,
  input  [31:0] io_wrData_user,
  input  [5:0]  io_rdReq_bits,
  input         io_rdReq_valid,
  output        io_rdReq_ready,
  output [1:0]  io_rdResp_bits_resp,
  output [31:0] io_rdResp_bits_user,
  output        io_rdResp_valid,
  input         io_rdResp_ready
);

  wire [33:0] _queueRd_ram_dataOutB;
  wire [33:0] _sram_sram_ext_R0_data;
  wire        queueRd_sink_ready = io_rdResp_ready;
  wire [1:0]  queueRd_source_bits_resp = _sram_sram_ext_R0_data[33:32];
  wire [31:0] queueRd_source_bits_user = _sram_sram_ext_R0_data[31:0];
  reg  [2:0]  rdCounter_rCounter;
  wire        rdCounter_empty = rdCounter_rCounter == 3'h0;
  wire        rdCounter_full_ = rdCounter_rCounter == 3'h4;
  wire        rdCounter_incEn = ~rdCounter_full_ & io_rdReq_valid;
  reg         r;
  wire        queueRd_source_valid = r;
  wire        queueRd_sink_valid;
  wire        rdCounter_decEn = io_rdResp_ready & queueRd_sink_valid;
  reg  [1:0]  queueRd_enqPtr_value;
  reg  [1:0]  queueRd_deqPtr_value;
  reg         queueRd_maybeFull;
  wire        queueRd_ptrMatch = queueRd_enqPtr_value == queueRd_deqPtr_value;
  wire        queueRd_source_ready;
  wire        queueRd_doEnq = queueRd_source_ready & queueRd_source_valid;
  assign queueRd_sink_valid = ~(queueRd_ptrMatch & ~queueRd_maybeFull);
  assign queueRd_source_ready = ~(queueRd_ptrMatch & queueRd_maybeFull);
  wire [31:0] queueRd_sink_bits_user = _queueRd_ram_dataOutB[31:0];
  wire [1:0]  queueRd_sink_bits_resp = _queueRd_ram_dataOutB[33:32];
  always @(posedge clock) begin
    if (reset) begin
      rdCounter_rCounter <= 3'h0;
      queueRd_enqPtr_value <= 2'h0;
      queueRd_deqPtr_value <= 2'h0;
      queueRd_maybeFull <= 1'h0;
    end
    else begin
      automatic logic queueRd_doDeq = queueRd_sink_ready & queueRd_sink_valid;
      if (~(rdCounter_incEn & rdCounter_decEn)) begin
        if (rdCounter_incEn)
          rdCounter_rCounter <= rdCounter_rCounter + 3'h1;
        else if (rdCounter_decEn)
          rdCounter_rCounter <= rdCounter_rCounter - 3'h1;
      end
      if (queueRd_doEnq)
        queueRd_enqPtr_value <= queueRd_enqPtr_value + 2'h1;
      if (queueRd_doDeq)
        queueRd_deqPtr_value <= queueRd_deqPtr_value + 2'h1;
      if (queueRd_doEnq != queueRd_doDeq)
        queueRd_maybeFull <= queueRd_doEnq;
    end
    r <= rdCounter_incEn;
  end // always @(posedge)
  sram_sram_64x34 sram_sram_ext (
    .R0_addr (io_rdReq_bits),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_sram_sram_ext_R0_data),
    .W0_addr (io_wrAddr),
    .W0_en   (io_wrEn),
    .W0_clk  (clock),
    .W0_data ({io_wrData_resp, io_wrData_user})
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(2),
    .COUNT(4),
    .DATA_WIDTH(34)
  ) queueRd_ram (
    .clock    (clock),
    .addrA    (queueRd_enqPtr_value),
    .writeEnA (queueRd_doEnq),
    .dataInA  ({queueRd_source_bits_resp, queueRd_source_bits_user}),
    .addrB    (queueRd_deqPtr_value),
    .dataOutB (_queueRd_ram_dataOutB)
  );
  assign io_rdReq_ready = ~rdCounter_full_;
  assign io_rdResp_bits_resp = queueRd_sink_bits_resp;
  assign io_rdResp_bits_user = queueRd_sink_bits_user;
  assign io_rdResp_valid = queueRd_sink_valid;
endmodule

// VCS coverage exclude_file
module read_xIndexFill_64x8(
  input  [5:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [7:0] R0_data,
  input  [5:0] R1_addr,
  input        R1_en,
               R1_clk,
  output [7:0] R1_data,
  input  [5:0] R2_addr,
  input        R2_en,
               R2_clk,
  output [7:0] R2_data,
  input  [5:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [7:0] W0_data,
  input  [5:0] W1_addr,
  input        W1_en,
               W1_clk,
  input  [7:0] W1_data
);

  reg [7:0] Memory[0:63];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
    if (W1_en)
      Memory[W1_addr] <= W1_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 8'bx;
  assign R1_data = R1_en ? Memory[R1_addr] : 8'bx;
  assign R2_data = R2_en ? Memory[R2_addr] : 8'bx;
endmodule

// VCS coverage exclude_file
module read_bufferValid_256x1(
  input  [7:0] R0_addr,
  input        R0_en,
               R0_clk,
  output       R0_data,
  input  [7:0] W0_addr,
  input        W0_en,
               W0_clk,
               W0_data,
  input  [7:0] W1_addr,
  input        W1_en,
               W1_clk,
               W1_data
);

  reg Memory[0:255];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
    if (W1_en)
      Memory[W1_addr] <= W1_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 1'bx;
endmodule

// VCS coverage exclude_file
module write_bufferValid_64x1(
  input  [5:0] R0_addr,
  input        R0_en,
               R0_clk,
  output       R0_data,
  input  [5:0] W0_addr,
  input        W0_en,
               W0_clk,
               W0_data,
  input  [5:0] W1_addr,
  input        W1_en,
               W1_clk,
               W1_data
);

  reg Memory[0:63];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
    if (W1_en)
      Memory[W1_addr] <= W1_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 1'bx;
endmodule

module IdParallelize(
  input         clock,
                reset,
  input  [31:0] s_axi_ar_bits_addr,
  input  [7:0]  s_axi_ar_bits_len,
  input  [2:0]  s_axi_ar_bits_size,
  input  [1:0]  s_axi_ar_bits_burst,
  input         s_axi_ar_bits_lock,
  input  [3:0]  s_axi_ar_bits_cache,
  input  [2:0]  s_axi_ar_bits_prot,
  input  [3:0]  s_axi_ar_bits_qos,
                s_axi_ar_bits_region,
  input         s_axi_ar_valid,
  output        s_axi_ar_ready,
  output [63:0] s_axi_r_bits_data,
  output [1:0]  s_axi_r_bits_resp,
  output        s_axi_r_bits_last,
                s_axi_r_valid,
  input         s_axi_r_ready,
  input  [31:0] s_axi_aw_bits_addr,
  input  [7:0]  s_axi_aw_bits_len,
  input  [2:0]  s_axi_aw_bits_size,
  input  [1:0]  s_axi_aw_bits_burst,
  input         s_axi_aw_bits_lock,
  input  [3:0]  s_axi_aw_bits_cache,
  input  [2:0]  s_axi_aw_bits_prot,
  input  [3:0]  s_axi_aw_bits_qos,
                s_axi_aw_bits_region,
  input         s_axi_aw_valid,
  output        s_axi_aw_ready,
  input  [63:0] s_axi_w_bits_data,
  input  [7:0]  s_axi_w_bits_strb,
  input         s_axi_w_bits_last,
                s_axi_w_valid,
  output        s_axi_w_ready,
  output [1:0]  s_axi_b_bits_resp,
  output [31:0] s_axi_b_bits_user,
  output        s_axi_b_valid,
  input         s_axi_b_ready,
  output [5:0]  m_axi_ar_bits_id,
  output [31:0] m_axi_ar_bits_addr,
  output [7:0]  m_axi_ar_bits_len,
  output [2:0]  m_axi_ar_bits_size,
  output [1:0]  m_axi_ar_bits_burst,
  output        m_axi_ar_bits_lock,
  output [3:0]  m_axi_ar_bits_cache,
  output [2:0]  m_axi_ar_bits_prot,
  output [3:0]  m_axi_ar_bits_qos,
                m_axi_ar_bits_region,
  output        m_axi_ar_valid,
  input         m_axi_ar_ready,
  input  [5:0]  m_axi_r_bits_id,
  input  [63:0] m_axi_r_bits_data,
  input  [1:0]  m_axi_r_bits_resp,
  input         m_axi_r_bits_last,
                m_axi_r_valid,
  output [5:0]  m_axi_aw_bits_id,
  output [31:0] m_axi_aw_bits_addr,
  output [7:0]  m_axi_aw_bits_len,
  output [2:0]  m_axi_aw_bits_size,
  output [1:0]  m_axi_aw_bits_burst,
  output        m_axi_aw_bits_lock,
  output [3:0]  m_axi_aw_bits_cache,
  output [2:0]  m_axi_aw_bits_prot,
  output [3:0]  m_axi_aw_bits_qos,
                m_axi_aw_bits_region,
  output        m_axi_aw_valid,
  input         m_axi_aw_ready,
  output [63:0] m_axi_w_bits_data,
  output [7:0]  m_axi_w_bits_strb,
  output        m_axi_w_bits_last,
                m_axi_w_valid,
  input         m_axi_w_ready,
  input  [5:0]  m_axi_b_bits_id,
  input  [1:0]  m_axi_b_bits_resp,
  input  [31:0] m_axi_b_bits_user,
  input         m_axi_b_valid
);

  wire [66:0] _read_m_ar_queue0_ram_dataOutB;
  wire [66:0] _write_m_aw_queue0_ram_dataOutB;
  wire [66:0] _read_s_r_queue0_ram_dataOutB;
  wire [33:0] _write_s_b_queue0_ram_dataOutB;
  wire        _write_bufferPayload_io_rdReq_ready;
  wire        _write_bufferValid_ext_R0_data;
  wire        _read_bufferPayload_io_rdReq_ready;
  wire        _read_bufferValid_ext_R0_data;
  wire [7:0]  _read_xIndexFill_ext_R0_data;
  wire [7:0]  _read_xIndexFill_ext_R1_data;
  wire [7:0]  _read_xIndexFill_ext_R2_data;
  wire [31:0] read_m_ar_bits_addr = s_axi_ar_bits_addr;
  wire [7:0]  read_m_ar_bits_len = s_axi_ar_bits_len;
  wire [2:0]  read_m_ar_bits_size = s_axi_ar_bits_size;
  wire [1:0]  read_m_ar_bits_burst = s_axi_ar_bits_burst;
  wire        read_m_ar_bits_lock = s_axi_ar_bits_lock;
  wire [3:0]  read_m_ar_bits_cache = s_axi_ar_bits_cache;
  wire [2:0]  read_m_ar_bits_prot = s_axi_ar_bits_prot;
  wire [3:0]  read_m_ar_bits_qos = s_axi_ar_bits_qos;
  wire [3:0]  read_m_ar_bits_region = s_axi_ar_bits_region;
  wire [31:0] write_m_aw_bits_addr = s_axi_aw_bits_addr;
  wire [7:0]  write_m_aw_bits_len = s_axi_aw_bits_len;
  wire [2:0]  write_m_aw_bits_size = s_axi_aw_bits_size;
  wire [1:0]  write_m_aw_bits_burst = s_axi_aw_bits_burst;
  wire        write_m_aw_bits_lock = s_axi_aw_bits_lock;
  wire [3:0]  write_m_aw_bits_cache = s_axi_aw_bits_cache;
  wire [2:0]  write_m_aw_bits_prot = s_axi_aw_bits_prot;
  wire [3:0]  write_m_aw_bits_qos = s_axi_aw_bits_qos;
  wire [3:0]  write_m_aw_bits_region = s_axi_aw_bits_region;
  reg  [6:0]  read_nextIdFill;
  reg  [7:0]  read_nextIndexFill;
  reg  [7:0]  read_nextIndexDrain;
  reg  [8:0]  read_bufferAvailable;
  reg  [6:0]  read_xCount_rCounter;
  wire        read_xCount_empty = read_xCount_rCounter == 7'h0;
  wire        read_xCount_full_ = read_xCount_rCounter == 7'h40;
  wire [8:0]  _GEN = {1'h0, s_axi_ar_bits_len + 8'h1};
  wire        read_m_ar_ready;
  wire        s_axi_ar_ready_0 =
    read_m_ar_ready & ~(read_nextIdFill[6]) & read_bufferAvailable >= _GEN;
  wire [5:0]  read_m_ar_bits_id = read_nextIdFill[5:0];
  wire        _read_T_7 = s_axi_ar_ready_0 & s_axi_ar_valid;
  wire        read_xCount_incEn;
  assign read_xCount_incEn = _read_T_7;
  wire        read_m_ar_valid;
  assign read_m_ar_valid = _read_T_7;
  wire        _read_T_5 =
    _read_bufferPayload_io_rdReq_ready & _read_bufferValid_ext_R0_data;
  wire        read_s_r_ready;
  wire        read_s_r_valid;
  wire        read_s_r_queue0_doEnq = read_s_r_ready & read_s_r_valid;
  wire        read_s_r_bits_last;
  wire        read_xCount_decEn = read_s_r_queue0_doEnq & read_s_r_bits_last;
  reg  [6:0]  write_nextIdFill;
  reg  [5:0]  write_nextIdDrain;
  reg  [6:0]  write_xCount_rCounter;
  wire        write_xCount_empty = write_xCount_rCounter == 7'h0;
  wire        write_xCount_full_ = write_xCount_rCounter == 7'h40;
  wire        write_m_aw_ready;
  wire        s_axi_aw_ready_0 = write_m_aw_ready & ~(write_nextIdFill[6]);
  wire [5:0]  write_m_aw_bits_id = write_nextIdFill[5:0];
  wire        _write_T_4 = s_axi_aw_ready_0 & s_axi_aw_valid;
  wire        write_xCount_incEn;
  assign write_xCount_incEn = _write_T_4;
  wire        write_m_aw_valid;
  assign write_m_aw_valid = _write_T_4;
  wire        _write_T_2 =
    _write_bufferPayload_io_rdReq_ready & _write_bufferValid_ext_R0_data;
  wire        write_s_b_ready;
  wire        write_s_b_valid;
  wire        write_xCount_decEn = write_s_b_ready & write_s_b_valid;
  reg         write_s_b_queue0_enqPtr_value;
  reg         write_s_b_queue0_deqPtr_value;
  reg         write_s_b_queue0_maybeFull;
  wire        write_s_b_queue0_ptrMatch =
    write_s_b_queue0_enqPtr_value == write_s_b_queue0_deqPtr_value;
  wire        write_s_b_queue0_empty =
    write_s_b_queue0_ptrMatch & ~write_s_b_queue0_maybeFull;
  wire [1:0]  write_s_b_bits_resp;
  wire [31:0] write_s_b_bits_user;
  assign write_s_b_ready = ~(write_s_b_queue0_ptrMatch & write_s_b_queue0_maybeFull);
  reg         read_s_r_queue0_enqPtr_value;
  reg         read_s_r_queue0_deqPtr_value;
  reg         read_s_r_queue0_maybeFull;
  wire        read_s_r_queue0_ptrMatch =
    read_s_r_queue0_enqPtr_value == read_s_r_queue0_deqPtr_value;
  wire        read_s_r_queue0_empty =
    read_s_r_queue0_ptrMatch & ~read_s_r_queue0_maybeFull;
  wire [63:0] read_s_r_bits_data;
  wire [1:0]  read_s_r_bits_resp;
  assign read_s_r_ready = ~(read_s_r_queue0_ptrMatch & read_s_r_queue0_maybeFull);
  reg         write_m_aw_queue0_enqPtr_value;
  reg         write_m_aw_queue0_deqPtr_value;
  reg         write_m_aw_queue0_maybeFull;
  wire        write_m_aw_queue0_ptrMatch =
    write_m_aw_queue0_enqPtr_value == write_m_aw_queue0_deqPtr_value;
  wire        write_m_aw_queue0_empty =
    write_m_aw_queue0_ptrMatch & ~write_m_aw_queue0_maybeFull;
  wire        write_m_aw_queue0_doEnq = write_m_aw_ready & write_m_aw_valid;
  assign write_m_aw_ready = ~(write_m_aw_queue0_ptrMatch & write_m_aw_queue0_maybeFull);
  reg         read_m_ar_queue0_enqPtr_value;
  reg         read_m_ar_queue0_deqPtr_value;
  reg         read_m_ar_queue0_maybeFull;
  wire        read_m_ar_queue0_ptrMatch =
    read_m_ar_queue0_enqPtr_value == read_m_ar_queue0_deqPtr_value;
  wire        read_m_ar_queue0_empty =
    read_m_ar_queue0_ptrMatch & ~read_m_ar_queue0_maybeFull;
  wire        read_m_ar_queue0_doEnq = read_m_ar_ready & read_m_ar_valid;
  assign read_m_ar_ready = ~(read_m_ar_queue0_ptrMatch & read_m_ar_queue0_maybeFull);
  always @(posedge clock) begin
    if (reset) begin
      read_nextIdFill <= 7'h0;
      read_nextIndexFill <= 8'h0;
      read_nextIndexDrain <= 8'h0;
      read_bufferAvailable <= 9'h100;
      read_xCount_rCounter <= 7'h0;
      write_xCount_rCounter <= 7'h0;
      write_s_b_queue0_enqPtr_value <= 1'h0;
      write_s_b_queue0_deqPtr_value <= 1'h0;
      write_s_b_queue0_maybeFull <= 1'h0;
      read_s_r_queue0_enqPtr_value <= 1'h0;
      read_s_r_queue0_deqPtr_value <= 1'h0;
      read_s_r_queue0_maybeFull <= 1'h0;
      write_m_aw_queue0_enqPtr_value <= 1'h0;
      write_m_aw_queue0_deqPtr_value <= 1'h0;
      write_m_aw_queue0_maybeFull <= 1'h0;
      read_m_ar_queue0_enqPtr_value <= 1'h0;
      read_m_ar_queue0_deqPtr_value <= 1'h0;
      read_m_ar_queue0_maybeFull <= 1'h0;
    end
    else begin
      automatic logic read_m_ar_queue0_doDeq = m_axi_ar_ready & ~read_m_ar_queue0_empty;
      automatic logic write_s_b_queue0_doDeq = s_axi_b_ready & ~write_s_b_queue0_empty;
      automatic logic read_s_r_queue0_doDeq = s_axi_r_ready & ~read_s_r_queue0_empty;
      automatic logic write_m_aw_queue0_doDeq = m_axi_aw_ready & ~write_m_aw_queue0_empty;
      if (read_xCount_empty & ~_read_T_7) begin
        read_nextIdFill <= 7'h0;
        read_nextIndexFill <= 8'h0;
        read_nextIndexDrain <= 8'h0;
        read_bufferAvailable <= 9'h100;
      end
      else begin
        if (_read_T_7) begin
          read_nextIdFill <= read_nextIdFill + 7'h1;
          read_nextIndexFill <= read_nextIndexFill + s_axi_ar_bits_len + 8'h1;
          read_bufferAvailable <= read_bufferAvailable - _GEN;
        end
        if (_read_T_5)
          read_nextIndexDrain <= read_nextIndexDrain + 8'h1;
      end
      if (~(read_xCount_incEn & read_xCount_decEn)) begin
        if (read_xCount_incEn)
          read_xCount_rCounter <= read_xCount_rCounter + 7'h1;
        else if (read_xCount_decEn)
          read_xCount_rCounter <= read_xCount_rCounter - 7'h1;
      end
      if (~(write_xCount_incEn & write_xCount_decEn)) begin
        if (write_xCount_incEn)
          write_xCount_rCounter <= write_xCount_rCounter + 7'h1;
        else if (write_xCount_decEn)
          write_xCount_rCounter <= write_xCount_rCounter - 7'h1;
      end
      if (write_xCount_decEn)
        write_s_b_queue0_enqPtr_value <= write_s_b_queue0_enqPtr_value - 1'h1;
      if (write_s_b_queue0_doDeq)
        write_s_b_queue0_deqPtr_value <= write_s_b_queue0_deqPtr_value - 1'h1;
      if (write_xCount_decEn != write_s_b_queue0_doDeq)
        write_s_b_queue0_maybeFull <= write_xCount_decEn;
      if (read_s_r_queue0_doEnq)
        read_s_r_queue0_enqPtr_value <= read_s_r_queue0_enqPtr_value - 1'h1;
      if (read_s_r_queue0_doDeq)
        read_s_r_queue0_deqPtr_value <= read_s_r_queue0_deqPtr_value - 1'h1;
      if (read_s_r_queue0_doEnq != read_s_r_queue0_doDeq)
        read_s_r_queue0_maybeFull <= read_s_r_queue0_doEnq;
      if (write_m_aw_queue0_doEnq)
        write_m_aw_queue0_enqPtr_value <= write_m_aw_queue0_enqPtr_value - 1'h1;
      if (write_m_aw_queue0_doDeq)
        write_m_aw_queue0_deqPtr_value <= write_m_aw_queue0_deqPtr_value - 1'h1;
      if (write_m_aw_queue0_doEnq != write_m_aw_queue0_doDeq)
        write_m_aw_queue0_maybeFull <= write_m_aw_queue0_doEnq;
      if (read_m_ar_queue0_doEnq)
        read_m_ar_queue0_enqPtr_value <= read_m_ar_queue0_enqPtr_value - 1'h1;
      if (read_m_ar_queue0_doDeq)
        read_m_ar_queue0_deqPtr_value <= read_m_ar_queue0_deqPtr_value - 1'h1;
      if (read_m_ar_queue0_doEnq != read_m_ar_queue0_doDeq)
        read_m_ar_queue0_maybeFull <= read_m_ar_queue0_doEnq;
    end
    if (write_xCount_empty & ~_write_T_4) begin
      write_nextIdFill <= 7'h0;
      write_nextIdDrain <= 6'h0;
    end
    else begin
      if (_write_T_4)
        write_nextIdFill <= write_nextIdFill + 7'h1;
      if (_write_T_2)
        write_nextIdDrain <= write_nextIdDrain + 6'h1;
    end
  end // always @(posedge)
  read_xIndexFill_64x8 read_xIndexFill_ext (
    .R0_addr (m_axi_r_bits_id),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_read_xIndexFill_ext_R0_data),
    .R1_addr (m_axi_r_bits_id),
    .R1_en   (m_axi_r_valid),
    .R1_clk  (clock),
    .R1_data (_read_xIndexFill_ext_R1_data),
    .R2_addr (m_axi_r_bits_id),
    .R2_en   (m_axi_r_valid),
    .R2_clk  (clock),
    .R2_data (_read_xIndexFill_ext_R2_data),
    .W0_addr (m_axi_r_bits_id),
    .W0_en   (m_axi_r_valid),
    .W0_clk  (clock),
    .W0_data (_read_xIndexFill_ext_R2_data + 8'h1),
    .W1_addr (read_nextIdFill[5:0]),
    .W1_en   (_read_T_7),
    .W1_clk  (clock),
    .W1_data (read_nextIndexFill)
  );
  read_bufferValid_256x1 read_bufferValid_ext (
    .R0_addr (read_nextIndexDrain),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_read_bufferValid_ext_R0_data),
    .W0_addr (read_nextIndexDrain),
    .W0_en   (_read_T_5),
    .W0_clk  (clock),
    .W0_data (1'h0),
    .W1_addr (_read_xIndexFill_ext_R1_data),
    .W1_en   (m_axi_r_valid),
    .W1_clk  (clock),
    .W1_data (1'h1)
  );
  SyncWriteElasticReadMemory read_bufferPayload (
    .clock               (clock),
    .reset               (reset),
    .io_wrEn             (m_axi_r_valid),
    .io_wrAddr           (_read_xIndexFill_ext_R0_data),
    .io_wrData_data      (m_axi_r_bits_data),
    .io_wrData_resp      (m_axi_r_bits_resp),
    .io_wrData_last      (m_axi_r_bits_last),
    .io_rdReq_bits       (read_nextIndexDrain),
    .io_rdReq_valid      (_read_bufferValid_ext_R0_data),
    .io_rdReq_ready      (_read_bufferPayload_io_rdReq_ready),
    .io_rdResp_bits_data (read_s_r_bits_data),
    .io_rdResp_bits_resp (read_s_r_bits_resp),
    .io_rdResp_bits_last (read_s_r_bits_last),
    .io_rdResp_valid     (read_s_r_valid),
    .io_rdResp_ready     (read_s_r_ready)
  );
  write_bufferValid_64x1 write_bufferValid_ext (
    .R0_addr (write_nextIdDrain),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_write_bufferValid_ext_R0_data),
    .W0_addr (write_nextIdDrain),
    .W0_en   (_write_T_2),
    .W0_clk  (clock),
    .W0_data (1'h0),
    .W1_addr (m_axi_b_bits_id),
    .W1_en   (m_axi_b_valid),
    .W1_clk  (clock),
    .W1_data (1'h1)
  );
  SyncWriteElasticReadMemory_1 write_bufferPayload (
    .clock               (clock),
    .reset               (reset),
    .io_wrEn             (m_axi_b_valid),
    .io_wrAddr           (m_axi_b_bits_id),
    .io_wrData_resp      (m_axi_b_bits_resp),
    .io_wrData_user      (m_axi_b_bits_user),
    .io_rdReq_bits       (write_nextIdDrain),
    .io_rdReq_valid      (_write_bufferValid_ext_R0_data),
    .io_rdReq_ready      (_write_bufferPayload_io_rdReq_ready),
    .io_rdResp_bits_resp (write_s_b_bits_resp),
    .io_rdResp_bits_user (write_s_b_bits_user),
    .io_rdResp_valid     (write_s_b_valid),
    .io_rdResp_ready     (write_s_b_ready)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(34)
  ) write_s_b_queue0_ram (
    .clock    (clock),
    .addrA    (write_s_b_queue0_enqPtr_value),
    .writeEnA (write_xCount_decEn),
    .dataInA  ({write_s_b_bits_resp, write_s_b_bits_user}),
    .addrB    (write_s_b_queue0_deqPtr_value),
    .dataOutB (_write_s_b_queue0_ram_dataOutB)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(67)
  ) read_s_r_queue0_ram (
    .clock    (clock),
    .addrA    (read_s_r_queue0_enqPtr_value),
    .writeEnA (read_s_r_queue0_doEnq),
    .dataInA  ({read_s_r_bits_data, read_s_r_bits_resp, read_s_r_bits_last}),
    .addrB    (read_s_r_queue0_deqPtr_value),
    .dataOutB (_read_s_r_queue0_ram_dataOutB)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(67)
  ) write_m_aw_queue0_ram (
    .clock    (clock),
    .addrA    (write_m_aw_queue0_enqPtr_value),
    .writeEnA (write_m_aw_queue0_doEnq),
    .dataInA
      ({write_m_aw_bits_id,
        write_m_aw_bits_addr,
        write_m_aw_bits_len,
        write_m_aw_bits_size,
        write_m_aw_bits_burst,
        write_m_aw_bits_lock,
        write_m_aw_bits_cache,
        write_m_aw_bits_prot,
        write_m_aw_bits_qos,
        write_m_aw_bits_region}),
    .addrB    (write_m_aw_queue0_deqPtr_value),
    .dataOutB (_write_m_aw_queue0_ram_dataOutB)
  );
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(67)
  ) read_m_ar_queue0_ram (
    .clock    (clock),
    .addrA    (read_m_ar_queue0_enqPtr_value),
    .writeEnA (read_m_ar_queue0_doEnq),
    .dataInA
      ({read_m_ar_bits_id,
        read_m_ar_bits_addr,
        read_m_ar_bits_len,
        read_m_ar_bits_size,
        read_m_ar_bits_burst,
        read_m_ar_bits_lock,
        read_m_ar_bits_cache,
        read_m_ar_bits_prot,
        read_m_ar_bits_qos,
        read_m_ar_bits_region}),
    .addrB    (read_m_ar_queue0_deqPtr_value),
    .dataOutB (_read_m_ar_queue0_ram_dataOutB)
  );
  assign s_axi_ar_ready = s_axi_ar_ready_0;
  assign s_axi_r_bits_data = _read_s_r_queue0_ram_dataOutB[66:3];
  assign s_axi_r_bits_resp = _read_s_r_queue0_ram_dataOutB[2:1];
  assign s_axi_r_bits_last = _read_s_r_queue0_ram_dataOutB[0];
  assign s_axi_r_valid = ~read_s_r_queue0_empty;
  assign s_axi_aw_ready = s_axi_aw_ready_0;
  assign s_axi_w_ready = m_axi_w_ready;
  assign s_axi_b_bits_resp = _write_s_b_queue0_ram_dataOutB[33:32];
  assign s_axi_b_bits_user = _write_s_b_queue0_ram_dataOutB[31:0];
  assign s_axi_b_valid = ~write_s_b_queue0_empty;
  assign m_axi_ar_bits_id = _read_m_ar_queue0_ram_dataOutB[66:61];
  assign m_axi_ar_bits_addr = _read_m_ar_queue0_ram_dataOutB[60:29];
  assign m_axi_ar_bits_len = _read_m_ar_queue0_ram_dataOutB[28:21];
  assign m_axi_ar_bits_size = _read_m_ar_queue0_ram_dataOutB[20:18];
  assign m_axi_ar_bits_burst = _read_m_ar_queue0_ram_dataOutB[17:16];
  assign m_axi_ar_bits_lock = _read_m_ar_queue0_ram_dataOutB[15];
  assign m_axi_ar_bits_cache = _read_m_ar_queue0_ram_dataOutB[14:11];
  assign m_axi_ar_bits_prot = _read_m_ar_queue0_ram_dataOutB[10:8];
  assign m_axi_ar_bits_qos = _read_m_ar_queue0_ram_dataOutB[7:4];
  assign m_axi_ar_bits_region = _read_m_ar_queue0_ram_dataOutB[3:0];
  assign m_axi_ar_valid = ~read_m_ar_queue0_empty;
  assign m_axi_aw_bits_id = _write_m_aw_queue0_ram_dataOutB[66:61];
  assign m_axi_aw_bits_addr = _write_m_aw_queue0_ram_dataOutB[60:29];
  assign m_axi_aw_bits_len = _write_m_aw_queue0_ram_dataOutB[28:21];
  assign m_axi_aw_bits_size = _write_m_aw_queue0_ram_dataOutB[20:18];
  assign m_axi_aw_bits_burst = _write_m_aw_queue0_ram_dataOutB[17:16];
  assign m_axi_aw_bits_lock = _write_m_aw_queue0_ram_dataOutB[15];
  assign m_axi_aw_bits_cache = _write_m_aw_queue0_ram_dataOutB[14:11];
  assign m_axi_aw_bits_prot = _write_m_aw_queue0_ram_dataOutB[10:8];
  assign m_axi_aw_bits_qos = _write_m_aw_queue0_ram_dataOutB[7:4];
  assign m_axi_aw_bits_region = _write_m_aw_queue0_ram_dataOutB[3:0];
  assign m_axi_aw_valid = ~write_m_aw_queue0_empty;
  assign m_axi_w_bits_data = s_axi_w_bits_data;
  assign m_axi_w_bits_strb = s_axi_w_bits_strb;
  assign m_axi_w_bits_last = s_axi_w_bits_last;
  assign m_axi_w_valid = s_axi_w_valid;
endmodule

module IdParallelize_Tbtop1_6(
  input         clock,
                reset,
  output        S_AXI_ARREADY,
  input         S_AXI_ARVALID,
  input  [31:0] S_AXI_ARADDR,
  input  [7:0]  S_AXI_ARLEN,
  input  [2:0]  S_AXI_ARSIZE,
  input  [1:0]  S_AXI_ARBURST,
  input         S_AXI_ARLOCK,
  input  [3:0]  S_AXI_ARCACHE,
  input  [2:0]  S_AXI_ARPROT,
  input  [3:0]  S_AXI_ARQOS,
                S_AXI_ARREGION,
  input         S_AXI_RREADY,
  output        S_AXI_RVALID,
  output [63:0] S_AXI_RDATA,
  output [1:0]  S_AXI_RRESP,
  output        S_AXI_RLAST,
                S_AXI_AWREADY,
  input         S_AXI_AWVALID,
  input  [31:0] S_AXI_AWADDR,
  input  [7:0]  S_AXI_AWLEN,
  input  [2:0]  S_AXI_AWSIZE,
  input  [1:0]  S_AXI_AWBURST,
  input         S_AXI_AWLOCK,
  input  [3:0]  S_AXI_AWCACHE,
  input  [2:0]  S_AXI_AWPROT,
  input  [3:0]  S_AXI_AWQOS,
                S_AXI_AWREGION,
  output        S_AXI_WREADY,
  input         S_AXI_WVALID,
  input  [63:0] S_AXI_WDATA,
  input  [7:0]  S_AXI_WSTRB,
  input         S_AXI_WLAST,
                S_AXI_BREADY,
  output        S_AXI_BVALID,
  output [1:0]  S_AXI_BRESP,
  output [31:0] S_AXI_BUSER,
  input         M_AXI_ARREADY,
  output        M_AXI_ARVALID,
  output [5:0]  M_AXI_ARID,
  output [31:0] M_AXI_ARADDR,
  output [7:0]  M_AXI_ARLEN,
  output [2:0]  M_AXI_ARSIZE,
  output [1:0]  M_AXI_ARBURST,
  output        M_AXI_ARLOCK,
  output [3:0]  M_AXI_ARCACHE,
  output [2:0]  M_AXI_ARPROT,
  output [3:0]  M_AXI_ARQOS,
                M_AXI_ARREGION,
  output        M_AXI_RREADY,
  input         M_AXI_RVALID,
  input  [5:0]  M_AXI_RID,
  input  [63:0] M_AXI_RDATA,
  input  [1:0]  M_AXI_RRESP,
  input         M_AXI_RLAST,
                M_AXI_AWREADY,
  output        M_AXI_AWVALID,
  output [5:0]  M_AXI_AWID,
  output [31:0] M_AXI_AWADDR,
  output [7:0]  M_AXI_AWLEN,
  output [2:0]  M_AXI_AWSIZE,
  output [1:0]  M_AXI_AWBURST,
  output        M_AXI_AWLOCK,
  output [3:0]  M_AXI_AWCACHE,
  output [2:0]  M_AXI_AWPROT,
  output [3:0]  M_AXI_AWQOS,
                M_AXI_AWREGION,
  input         M_AXI_WREADY,
  output        M_AXI_WVALID,
  output [63:0] M_AXI_WDATA,
  output [7:0]  M_AXI_WSTRB,
  output        M_AXI_WLAST,
                M_AXI_BREADY,
  input         M_AXI_BVALID,
  input  [5:0]  M_AXI_BID,
  input  [1:0]  M_AXI_BRESP,
  input  [31:0] M_AXI_BUSER
);

  IdParallelize dut (
    .clock                (clock),
    .reset                (reset),
    .s_axi_ar_bits_addr   (S_AXI_ARADDR),
    .s_axi_ar_bits_len    (S_AXI_ARLEN),
    .s_axi_ar_bits_size   (S_AXI_ARSIZE),
    .s_axi_ar_bits_burst  (S_AXI_ARBURST),
    .s_axi_ar_bits_lock   (S_AXI_ARLOCK),
    .s_axi_ar_bits_cache  (S_AXI_ARCACHE),
    .s_axi_ar_bits_prot   (S_AXI_ARPROT),
    .s_axi_ar_bits_qos    (S_AXI_ARQOS),
    .s_axi_ar_bits_region (S_AXI_ARREGION),
    .s_axi_ar_valid       (S_AXI_ARVALID),
    .s_axi_ar_ready       (S_AXI_ARREADY),
    .s_axi_r_bits_data    (S_AXI_RDATA),
    .s_axi_r_bits_resp    (S_AXI_RRESP),
    .s_axi_r_bits_last    (S_AXI_RLAST),
    .s_axi_r_valid        (S_AXI_RVALID),
    .s_axi_r_ready        (S_AXI_RREADY),
    .s_axi_aw_bits_addr   (S_AXI_AWADDR),
    .s_axi_aw_bits_len    (S_AXI_AWLEN),
    .s_axi_aw_bits_size   (S_AXI_AWSIZE),
    .s_axi_aw_bits_burst  (S_AXI_AWBURST),
    .s_axi_aw_bits_lock   (S_AXI_AWLOCK),
    .s_axi_aw_bits_cache  (S_AXI_AWCACHE),
    .s_axi_aw_bits_prot   (S_AXI_AWPROT),
    .s_axi_aw_bits_qos    (S_AXI_AWQOS),
    .s_axi_aw_bits_region (S_AXI_AWREGION),
    .s_axi_aw_valid       (S_AXI_AWVALID),
    .s_axi_aw_ready       (S_AXI_AWREADY),
    .s_axi_w_bits_data    (S_AXI_WDATA),
    .s_axi_w_bits_strb    (S_AXI_WSTRB),
    .s_axi_w_bits_last    (S_AXI_WLAST),
    .s_axi_w_valid        (S_AXI_WVALID),
    .s_axi_w_ready        (S_AXI_WREADY),
    .s_axi_b_bits_resp    (S_AXI_BRESP),
    .s_axi_b_bits_user    (S_AXI_BUSER),
    .s_axi_b_valid        (S_AXI_BVALID),
    .s_axi_b_ready        (S_AXI_BREADY),
    .m_axi_ar_bits_id     (M_AXI_ARID),
    .m_axi_ar_bits_addr   (M_AXI_ARADDR),
    .m_axi_ar_bits_len    (M_AXI_ARLEN),
    .m_axi_ar_bits_size   (M_AXI_ARSIZE),
    .m_axi_ar_bits_burst  (M_AXI_ARBURST),
    .m_axi_ar_bits_lock   (M_AXI_ARLOCK),
    .m_axi_ar_bits_cache  (M_AXI_ARCACHE),
    .m_axi_ar_bits_prot   (M_AXI_ARPROT),
    .m_axi_ar_bits_qos    (M_AXI_ARQOS),
    .m_axi_ar_bits_region (M_AXI_ARREGION),
    .m_axi_ar_valid       (M_AXI_ARVALID),
    .m_axi_ar_ready       (M_AXI_ARREADY),
    .m_axi_r_bits_id      (M_AXI_RID),
    .m_axi_r_bits_data    (M_AXI_RDATA),
    .m_axi_r_bits_resp    (M_AXI_RRESP),
    .m_axi_r_bits_last    (M_AXI_RLAST),
    .m_axi_r_valid        (M_AXI_RVALID),
    .m_axi_aw_bits_id     (M_AXI_AWID),
    .m_axi_aw_bits_addr   (M_AXI_AWADDR),
    .m_axi_aw_bits_len    (M_AXI_AWLEN),
    .m_axi_aw_bits_size   (M_AXI_AWSIZE),
    .m_axi_aw_bits_burst  (M_AXI_AWBURST),
    .m_axi_aw_bits_lock   (M_AXI_AWLOCK),
    .m_axi_aw_bits_cache  (M_AXI_AWCACHE),
    .m_axi_aw_bits_prot   (M_AXI_AWPROT),
    .m_axi_aw_bits_qos    (M_AXI_AWQOS),
    .m_axi_aw_bits_region (M_AXI_AWREGION),
    .m_axi_aw_valid       (M_AXI_AWVALID),
    .m_axi_aw_ready       (M_AXI_AWREADY),
    .m_axi_w_bits_data    (M_AXI_WDATA),
    .m_axi_w_bits_strb    (M_AXI_WSTRB),
    .m_axi_w_bits_last    (M_AXI_WLAST),
    .m_axi_w_valid        (M_AXI_WVALID),
    .m_axi_w_ready        (M_AXI_WREADY),
    .m_axi_b_bits_id      (M_AXI_BID),
    .m_axi_b_bits_resp    (M_AXI_BRESP),
    .m_axi_b_bits_user    (M_AXI_BUSER),
    .m_axi_b_valid        (M_AXI_BVALID)
  );
  assign M_AXI_RREADY = 1'h1;
  assign M_AXI_BREADY = 1'h1;
endmodule

